import { lazy, Suspense, useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowUpRight, ChevronDown, ClipboardCheck, ClipboardList, FileText, LayoutDashboard, Loader2, LogOut, Menu, MessageSquareText, Plus, Radio, RefreshCw, Settings2, ShieldAlert, Smartphone, Waypoints, Wifi, WifiOff, X } from 'lucide-react';
import { registerSW } from 'virtual:pwa-register';
import { AppContext } from './context';
import { api, ApiError, setCsrf, synchronize, snapshotWithHistory } from './api';
import { db, enqueue, localPlans, queueRows, saveSnapshot } from './db';
import { Auth } from './Auth';
import { Toast } from './Toast';
import { projectSnapshot } from './local';
import { Overview } from './Overview';
import { Badge, Button, Field, Modal, Notice, Submit } from './ui';
import { arr, nameOf, roleLabel, timeOf, type Account, type Entity, type Outbox, type Snapshot } from './types';

const Plans=lazy(()=>import('./Plans').then(m=>({default:m.Plans})));const Checks=lazy(()=>import('./Plans').then(m=>({default:m.Checks})));const Observations=lazy(()=>import('./Observations').then(m=>({default:m.Observations})));const Tasks=lazy(()=>import('./Tasks').then(m=>({default:m.Tasks})));const Graph=lazy(()=>import('./Graph').then(m=>({default:m.Graph})));const Readiness=lazy(()=>import('./Readiness').then(m=>({default:m.Readiness})));const Device=lazy(()=>import('./Device').then(m=>({default:m.Device})));const Sync=lazy(()=>import('./Device').then(m=>({default:m.Sync})));const Reports=lazy(()=>import('./Reports').then(m=>({default:m.Reports})));
const navigation=[{id:'overview',label:'Obraz sytuacji',icon:LayoutDashboard},{id:'plans',label:'Plany i przydziały',icon:ClipboardList},{id:'tasks',label:'Moje zadania',icon:ClipboardCheck},{id:'observations',label:'Meldunki',icon:MessageSquareText},{id:'checks',label:'Co sprawdzić',icon:ShieldAlert},{id:'graph',label:'Zależności',icon:Waypoints}];const administration=[{id:'readiness',label:'Gotowość',icon:Settings2},{id:'device',label:'To urządzenie',icon:Smartphone},{id:'sync',label:'Synchronizacja',icon:RefreshCw},{id:'reports',label:'Raport i historia',icon:FileText}];
function normalize(s: Snapshot):Snapshot {return {...s,incidents:arr(s.incidents),observations:arr(s.observations),assessments:arr(s.assessments),plans:arr(s.plans),actions:arr(s.actions),verifications:arr(s.verifications),allocations:arr(s.allocations),allocationScopes:arr(s.allocationScopes),evidence:arr(s.evidence),users:arr(s.users) as any};}
export function App() {
  const[account,setAccount]=useState<Account|null>(null);const[snapshot,setSnapshot]=useState<Snapshot|null>(null);const[loading,setLoading]=useState(true);const[bootstrap,setBootstrap]=useState(false);const[online,setOnline]=useState(false);const[authError,setAuthError]=useState('');const[queue,setQueue]=useState<Outbox[]>([]);const[drafts,setDrafts]=useState<Entity[]>([]);const[view,setView]=useState('overview');const[busy,setBusy]=useState(false);const[toast,setToast]=useState<{message:string;tone:string;category:'general'|'offline'|'sync-pending'}|null>(null);const[mobileNav,setMobileNav]=useState(false);const[incidentForm,setIncidentForm]=useState(false);const[activeIncidentId,setActiveIncidentId]=useState('');const[updateAvailable,setUpdateAvailable]=useState(false);const[clock,setClock]=useState(Date.now());const syncLock=useRef(false);const accountRef=useRef<Account|null>(null);const swUpdate=useRef<((reload?:boolean)=>Promise<void>)|null>(null);
  const inform=useCallback((message:string,tone='amber',category:'general'|'offline'|'sync-pending'='general')=>setToast({message,tone,category}),[]);
  useEffect(()=>{accountRef.current=account;},[account]);
  const reloadLocal=useCallback(async()=>{const current=accountRef.current;if(!current)return;const[rows,plans]=await Promise.all([queueRows(current.scope),localPlans(current.scope)]);setQueue(rows);setDrafts(plans);},[]);
  async function login(data:Entity){const me=data.user?data:await api('/api/auth/me');setCsrf(me.csrfToken);const scope=`${me.user.organizationId}:${me.user.id}`;const fresh=normalize(await snapshotWithHistory(scope));const now=Date.now();const next:Account={scope,user:me.user,csrfToken:me.csrfToken,serverEpoch:me.serverEpoch,offlineUntil:me.offlineExpiresAt||new Date(now+8*3600000).toISOString(),lastServerTime:Date.parse(fresh.serverTime)||now,lastLocalTime:now,lastObservedLocalTime:now};await db.transaction('rw',db.accounts,db.meta,async()=>{await db.accounts.put(next);await db.meta.put({key:'activeScope',value:scope});});await saveSnapshot(scope,fresh);accountRef.current=next;setAccount(next);setSnapshot(fresh);setOnline(true);setAuthError('');setView(me.user.role==='operator'?'tasks':'overview');await reloadLocal();}
  useEffect(()=>{let mounted=true;(async()=>{try{await db.open();const response=await api('/api/session');if(!mounted)return;setBootstrap(response.bootstrapRequired);if(response.user)await login(response);else setOnline(true);}catch(error){if(!mounted)return;if(error instanceof ApiError&&(error.status===0||error.status>=500)){setOnline(false);try{const scope=(await db.meta.get('activeScope'))?.value;const cached=scope?await db.accounts.get(scope):null;const local=scope?await db.snapshots.get(scope):null;if(cached&&local&&Date.parse(cached.offlineUntil)>Date.now()&&Date.now()>=(cached.lastObservedLocalTime||cached.lastLocalTime)-60000){setCsrf(cached.csrfToken);accountRef.current=cached;setAccount(cached);setSnapshot(normalize(local.snapshot));await reloadLocal();inform('Otworzono lokalny zapis. Serwer jest niedostępny; nowe zmiany trafią do kolejki.','amber','offline');}else setAuthError(cached?'Upoważnienie offline wygasło lub czas urządzenia jest niepewny. Połącz się z serwerem i zaloguj ponownie.':'Brak przygotowanego pakietu tego urządzenia. Pierwsze uruchomienie wymaga serwera LAN.');}catch{setAuthError('Pamięć urządzenia jest niedostępna. Nie można potwierdzić lokalnego zapisu.');}}else setAuthError(error instanceof Error?error.message:String(error));}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;};},[]);
  const refresh=useCallback(async()=>{const current=accountRef.current;if(!current||syncLock.current)return;syncLock.current=true;try{const result=await synchronize(current);const fresh=normalize(result.snapshot);setSnapshot(fresh);setOnline(true);const now=Date.now();const next={...current,user:result.me.user,csrfToken:result.me.csrfToken,serverEpoch:fresh.serverEpoch,offlineUntil:result.me.offlineExpiresAt||current.offlineUntil,lastServerTime:Date.parse(fresh.serverTime)||now,lastLocalTime:now,lastObservedLocalTime:now};await db.accounts.put(next);accountRef.current=next;setAccount(next);if(result.epochChanged)inform('Serwer ma nową epokę po odtworzeniu. Kolejka została zachowana i wymaga rozstrzygnięcia.');await reloadLocal();const unresolved=(await queueRows(current.scope)).some(row=>row.status!=='accepted'&&!row.result?.resolvedAt);setToast(previous=>previous?.category==='offline'||previous?.category==='sync-pending'&&!unresolved?null:previous);}catch(error){if(error instanceof ApiError&&(error.status===0||error.status>=500))setOnline(false);if(error instanceof ApiError&&error.status===401){setAuthError(error.message);setAccount(null);setSnapshot(null);accountRef.current=null;}throw error;}finally{syncLock.current=false;}},[reloadLocal,inform]);
  useEffect(()=>{if(!account)return;const check=()=>{refresh().catch(error=>{if(!(error instanceof ApiError&&(error.status===0||error.status>=500)))inform(error.message,'red');});};const focus=()=>{if(document.visibilityState==='visible')check();};window.addEventListener('online',check);document.addEventListener('visibilitychange',focus);const interval=setInterval(check,30000);const time=setInterval(()=>{const now=Date.now();setClock(now);const current=accountRef.current;if(current){const next={...current,lastObservedLocalTime:Math.max(now,current.lastObservedLocalTime||current.lastLocalTime)};accountRef.current=next;setAccount(next);db.accounts.put(next).catch(()=>inform('Nie można trwale zapisać stanu urządzenia. Wykonaj eksport kolejki.','red'));}},15000);return()=>{window.removeEventListener('online',check);document.removeEventListener('visibilitychange',focus);clearInterval(interval);clearInterval(time);};},[account?.scope,refresh,inform]);
  useEffect(()=>{swUpdate.current=registerSW({immediate:true,onNeedRefresh(){setUpdateAvailable(true);},onRegisterError(error){console.warn('PWA registration unavailable',error instanceof Error?error.name:'error');}});},[]);
  const run=useCallback(async<T,>(action:()=>Promise<T>,success?:string):Promise<T|undefined>=>{setBusy(true);try{const result=await action();if(success)inform(success,'green');return result;}catch(error){inform(error instanceof Error?error.message:String(error),'red');return undefined;}finally{setBusy(false);}},[inform]);
  async function command(type:string,payload:Entity,dependencies:string[]=[]){const current=accountRef.current;if(!current||!snapshot)throw new Error('Zaloguj się ponownie.');if(Date.parse(current.offlineUntil)<=Date.now()||Date.now()<(current.lastObservedLocalTime||current.lastLocalTime)-60000)throw new Error('Upoważnienie wygasło. Połącz się z serwerem.');let command;try{command=await enqueue(current.scope,snapshot,type,payload,dependencies);}catch{throw new Error('Nie zapisano zmiany. Pamięć urządzenia jest pełna lub niedostępna. Nie zamykaj formularza.');}await reloadLocal();try{await refresh();const result=await db.outbox.get(command.commandId);if(result?.status==='accepted'){inform('Serwer przyjął zmianę. Zapis i kursor zostały uzgodnione.','green');}else if(result&&['rejected','conflict'].includes(result.status)){throw new ApiError(result.result?.message||'Zmiana wymaga rozstrzygnięcia. Oryginał zachowano w kolejce.',409);}else inform('Zapisano na tym urządzeniu. Serwer jeszcze nie przyjął zmiany.','amber','sync-pending');}catch(error){if(error instanceof ApiError&&(error.status===0||error.status>=500)){inform('Zapisano na tym urządzeniu. Serwer jeszcze nie przyjął zmiany.','amber','sync-pending');return command.commandId;}throw error;}return command.commandId;}
  function navigate(id:string){setView(id);setMobileNav(false);window.scrollTo({top:0,behavior:'instant'});}
  async function logout(){if(online)await api('/api/auth/logout','POST',{});await db.meta.delete('activeScope');accountRef.current=null;setAccount(null);setSnapshot(null);setQueue([]);setDrafts([]);setCsrf('');setAuthError('');}
  if(loading)return <div className="loading-screen"><img src="/icon.svg" alt="MOST"/><Loader2 className="spin"/><p>Otwieranie lokalnego centrum ciągłości…</p></div>;
  if(!account||!snapshot)return <Auth bootstrap={bootstrap} onLogin={login} initialError={authError}/>;
  const expired=Date.parse(account.offlineUntil)<=clock||(!online&&clock<(account.lastObservedLocalTime||account.lastLocalTime)-60000);if(expired)return <main className="expired"><Notice tone="red">Dostęp offline wygasł lub czas urządzenia jest niepewny. Lokalna kolejka pozostaje zachowana.</Notice><Button kind="primary" onClick={()=>run(async()=>{await logout();})}>Wróć do logowania</Button></main>;
  const pending=queue.filter(q=>q.status!=='accepted'&&!q.result?.resolvedAt);const incident=snapshot.incidents.find(i=>i.id===activeIncidentId)||snapshot.incident||snapshot.incidents?.[0];const age=Math.max(0,Math.floor((clock-account.lastLocalTime)/60000));const canManage=['administrator','coordinator','owner'].includes(account.user.role);const canEdit=account.user.role!=='observer';
  const projected = projectSnapshot(snapshot,queue);projected.incident=incident;if(incident){for(const key of ['observations','plans','actions'] as const)projected[key]=projected[key].filter(item=>!item.incidentId||item.incidentId===incident.id);projected.verifications=projected.verifications.filter(v=>projected.actions.some(a=>a.id===v.actionId));}
  return <AppContext.Provider value={{account,snapshot:projected,online,queue,drafts,busy,view,navigate,run,command,refresh,reloadLocal,inform,canManage,canEdit}}><a className="skip-link" href="#main-content">Przejdź do treści</a><div className="app-shell"><aside className={`sidebar ${mobileNav?'open':''}`}><div className="sidebar-header"><button className="brand" onClick={()=>navigate('overview')}><img src="/icon.svg" alt=""/><span>MOST<span>CIĄGŁOŚĆ USŁUG</span></span></button><Button kind="icon mobile-only" onClick={()=>setMobileNav(false)} aria-label="Zamknij menu"><X size={22}/></Button></div><div className="org-selector"><div className="org-mark">M</div><span><strong>{snapshot.organizationName||'Centrum lokalne'}</strong><small>Centrum koordynacji</small></span><ChevronDown size={15}/></div><span className="nav-caption">KOORDYNACJA</span><nav aria-label="Koordynacja">{navigation.map(({id,label,icon:Icon})=><button key={id} onClick={()=>navigate(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon size={19}/><span>{label}</span>{id==='observations'&&snapshot.observations.length>0&&<span className="nav-count">{snapshot.observations.length}</span>}</button>)}</nav><span className="nav-caption second">ORGANIZACJA</span><nav aria-label="Organizacja">{administration.map(({id,label,icon:Icon})=><button key={id} onClick={()=>navigate(id)} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon size={18}/><span>{label}</span>{id==='sync'&&pending.length>0&&<span className="nav-count warning">{pending.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="local-ready"><span className={`status-dot ${online?'green':'amber'}`}/><span>{online?'Lokalny serwer dostępny':'Praca na urządzeniu'}<small>{online?'Sprawdzono przez API':'Brak aktualnych danych serwera'}</small></span></div><div className="user-block"><span className="avatar">{account.user.displayName?.split(' ').map(x=>x[0]).slice(0,2).join('')||'U'}</span><span><strong>{account.user.displayName}</strong><small>{roleLabel(account.user.role)}</small></span><Button kind="icon" onClick={()=>run(logout)} aria-label="Wyloguj, zachowując kolejkę"><LogOut size={17}/></Button></div></div></aside>{mobileNav&&<button className="nav-backdrop" aria-label="Zamknij menu" onClick={()=>setMobileNav(false)}/>}
  <div className="main-column"><header className="topbar"><div className="topbar-title"><Button kind="icon mobile-only" onClick={()=>setMobileNav(true)} aria-label="Otwórz menu"><Menu size={22}/></Button><span className="breadcrumb">Centrum ciągłości <span>/</span> <strong>{[...navigation,...administration].find(n=>n.id===view)?.label}</strong></span></div><div className="topbar-right"><span className="current-date">{new Date(clock).toLocaleDateString('pl-PL',{day:'numeric',month:'long',year:'numeric'})}</span><Badge tone="neutral">{snapshot.model.synthetic?'DANE SYNTETYCZNE':'ORGANIZACJA'}</Badge></div></header><div className={`connection-bar ${online?'connected':'disconnected'}`}><div><Badge tone={incident?.kind==='incident'?'red':'amber'}><Radio size={12}/>{incident?.kind==='incident'?'INCYDENT':'ĆWICZENIE'}</Badge><select className="incident-selector" aria-label="Aktywne ćwiczenie lub incydent" value={incident?.id||''} onChange={e=>setActiveIncidentId(e.target.value)}>{snapshot.incidents.length?snapshot.incidents.map(i=><option key={i.id} value={i.id}>{nameOf(i)}{i.status==='closed'?' (zamknięte)':''}</option>):<option value="">Brak otwartego zdarzenia</option>}</select>{canManage&&<button aria-label="Otwórz nowe ćwiczenie lub incydent" className="incident-add" disabled={!online} onClick={()=>setIncidentForm(true)}><Plus size={15}/></button>}</div><button onClick={()=>run(refresh)} className="connection-status">{online?<Wifi size={14}/>:<WifiOff size={14}/>}<span>{online?'Połączono z serwerem':'Brak serwera'} · dane {age===0?'sprzed chwili':`${age} min temu`}</span><span className="status-separator"/><span>{pending.length} nieuzgodnionych</span><RefreshCw size={13} className={busy?'spin':''}/></button></div>
  {updateAvailable&&<div className="update-notice"><span>Nowa wersja aplikacji jest gotowa. Bieżący widok nie zostanie samoczynnie przeładowany.</span><Button disabled={pending.length>0} onClick={()=>run(async()=>{await swUpdate.current?.(true);})}>Zastosuj po zapisaniu pracy</Button></div>}
  <main id="main-content" className="main-content" tabIndex={-1}><Suspense fallback={<div className="route-loading"><Loader2 className="spin"/>Otwieranie widoku…</div>}>{view==='overview'?<Overview/>:view==='plans'?<Plans/>:view==='checks'?<Checks/>:view==='observations'?<Observations/>:view==='tasks'?<Tasks/>:view==='graph'?<Graph/>:view==='readiness'?<Readiness/>:view==='device'?<Device/>:view==='sync'?<Sync/>:<Reports/>}</Suspense><footer className="page-footer"><span>MOST · ciągłość lokalnych usług</span><span>Model v{snapshot.model.revision} · lokalna instalacja</span></footer></main></div></div>
  {toast&&<Toast message={toast.message} tone={toast.tone} close={()=>setToast(null)}/>}
  {incidentForm&&<Modal title="Nowe ćwiczenie lub incydent" close={()=>setIncidentForm(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{const id=crypto.randomUUID();await command('incident.create',{id,title:String(f.get('title')),exercise:Boolean(snapshot.model.synthetic)});setActiveIncidentId(id);setIncidentForm(false);});}}><Field label="Nazwa"><input name="title" required defaultValue={snapshot.model.synthetic?'Ćwiczenie ciągłości usług':'Incydent lokalnych usług'}/></Field><Field label="Tryb"><select name="kind" value={snapshot.model.synthetic?'exercise':'incident'} disabled>{snapshot.model.synthetic?<option value="exercise">Ćwiczenie na osobnym zbiorze syntetycznym</option>:<option value="incident">Incydent w instalacji operacyjnej</option>}</select></Field><Notice>{snapshot.model.synthetic?'Ta instalacja służy ćwiczeniom i ma osobne dane. Próba nie potwierdza gotowości rzeczywistej infrastruktury.':'Ćwiczenia uruchamiaj w osobnej instalacji z syntetycznymi danymi, aby nie zmieniały rzeczywistych przydziałów.'}</Notice><Submit busy={busy}>Otwórz zdarzenie</Submit></form></Modal>}
  </AppContext.Provider>;
}

