import { useApp } from './context';
import { arr, nameOf, timeOf, type Entity } from './types';
import { Badge, Notice, Status } from './ui';

export function AssessmentDetails({observation}:{observation:Entity}){
  const {snapshot}=useApp();const assessments=arr(snapshot.assessments).filter(a=>(a.observationIds||[]).includes(observation.id));
  if(!assessments.length)return <p className="muted">Brak zapisanej oceny tego meldunku. Oryginał nie stanowi potwierdzonego stanu.</p>;
  const subjects=[...arr(snapshot.model.dependencies),...arr(snapshot.model.resources)];
  return <div className="assessment-history">{assessments.map((assessment,index)=>{
    const impact=assessment.computedImpact;const contradictions=arr(snapshot.observations).filter(o=>(assessment.contradictions||[]).includes(o.id));
    return <section className="scope-card" key={assessment.id}><h4>Ocena i wpływ na usługi</h4><p><Status value={assessment.state}/>{index<assessments.length-1&&<Badge>Ocena historyczna</Badge>} · {timeOf(assessment.approvedAt)} · {nameOf(arr(snapshot.users).find(u=>u.id===assessment.approvedBy))}</p><p>Przesłanki: {assessment.reason||assessment.rationale||'Nie zapisano opisu przesłanek.'}</p>{contradictions.length>0&&<details><summary>Sprzeczne meldunki ({contradictions.length})</summary>{contradictions.map(o=><blockquote key={o.id}>{o.original||o.text}<p>{o.source} · {timeOf(o.observedAt)} · <Status value={o.observedState||o.claimedState}/></p></blockquote>)}</details>}{impact?<><p>Obliczono {timeOf(impact.computedAt)}, model v{impact.modelRevision}. Dotknięte usługi: {(impact.affectedServiceIds||[]).map((id:string)=>nameOf(arr(snapshot.model.services).find(s=>s.id===id))).join(', ')||'Brak powiązanych usług w tym modelu'}.</p><p>Dotknięte tryby: {(impact.affectedModeIds||[]).map((id:string)=>nameOf(arr(snapshot.model.modes).find(m=>m.id===id))).join(', ')||'Brak'}. Czynności do przeglądu: {(impact.affectedActionIds||[]).length}.</p>{arr(impact.dependencyChanges).length>0&&<ul>{arr(impact.dependencyChanges).map(change=><li key={change.id}>{nameOf(subjects.find(s=>s.id===change.id))}: <Status value={change.before}/> → <Status value={change.after}/></li>)}</ul>}<h4>Brakujące sprawdzenia</h4>{arr(impact.missingChecks).length?<ul>{arr(impact.missingChecks).map((check,i)=><li key={`${check.subjectId}-${i}`}><strong>{nameOf(subjects.find(s=>s.id===check.subjectId))}</strong>: {check.question||'Potwierdź bieżący stan elementu.'} <Status value={check.state}/>{check.contact&&<p>Kontakt z zatwierdzonego katalogu: {typeof check.contact==='string'?check.contact:JSON.stringify(check.contact)}</p>}{check.verificationMinutes!=null&&<p>Przewidywany nakład: {check.verificationMinutes} min</p>}</li>)}</ul>:<p>Nie wskazano nieustalonych elementów w obliczonym zakresie.</p>}<Notice>To wpływ zależności i zasobów w zapisanej wersji. {impact.requiresReplanning?'Przelicz plan i ponownie sprawdź dotknięte czynności. ':''}Dostępne usługominuty i harmonogram wymagają osobnego obliczenia.</Notice></>:<Notice>Ta starsza ocena nie zawiera zapisanego wyliczenia wpływu. Wykonaj nową ocenę i przeliczenie planu na aktualnych danych.</Notice>}</section>;
  })}</div>;
}
