import { useEffect, useState } from 'react';
import { api } from './api';
import { useApp } from './context';
import { arr, nameOf, timeOf, type Entity } from './types';
import { Badge, Button, Field, Notice, Panel, SectionHeading } from './ui';
import { download } from './db';

function useIntegrationStatus(){const {online}=useApp();const [status,setStatus]=useState<Entity|null>(null);useEffect(()=>{let alive=true;if(online)api('/api/integrations').then(result=>{if(alive)setStatus(result);}).catch(()=>{if(alive)setStatus(null);});return()=>{alive=false;};},[online]);return status;}

export function AiExtractor({text,subjects,onAdopt}:{text:string;subjects:Entity[];onAdopt:(proposal:Entity)=>void}){
  const {online,run}=useApp();const status=useIntegrationStatus();const[consent,setConsent]=useState(false);const[selected,setSelected]=useState<string[]>([]);const[result,setResult]=useState<Entity|null>(null);const[busy,setBusy]=useState(false);
  const enabled=online&&status?.ai?.enabled&&status?.ai?.configured;
  return <details className="integration-panel"><summary>Opcjonalny szkic pól z wybranego tekstu</summary><Notice>Po zaznaczeniu zgody do zewnętrznego dostawcy trafi wyłącznie treść powyższego meldunku oraz identyfikatory i nazwy wybranych elementów. Szkic wymaga Twojego sprawdzenia.</Notice>{!enabled&&<p className="muted">Dodatek {online?'jest wyłączony lub nie został skonfigurowany':'wymaga połączenia z serwerem'}. Pełny formularz ręczny pozostaje dostępny.</p>}<span className="eyebrow">ELEMENTY, KTÓRE ZEZWALASZ PRZESŁAĆ (DO 10)</span><div className="checkbox-grid">{subjects.map(subject=><label className="checkbox" key={subject.id}><input type="checkbox" checked={selected.includes(subject.id)} disabled={!enabled||selected.length>=10&&!selected.includes(subject.id)} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,subject.id]:ids.filter(id=>id!==subject.id));setConsent(false);}}/>{nameOf(subject)}</label>)}</div><label className="checkbox"><input type="checkbox" checked={consent} disabled={!enabled} onChange={e=>setConsent(e.target.checked)}/>Zgadzam się przesłać wybrany tekst i wymienione elementy do dostawcy {status?.ai?.provider||'AI'}.</label><Button disabled={!enabled||!consent||!text.trim()||busy} onClick={()=>{setBusy(true);run(async()=>{setResult(await api('/api/ai/extract','POST',{text,subjectIds:selected,consent:true}));}).finally(()=>setBusy(false));}}>{busy?'Oczekiwanie na szkic…':'Prześlij i zaproponuj pola'}</Button>{result&&!result.proposal&&<Notice>{result.message||'Dodatek nie zwrócił poprawnego szkicu. Uzupełnij pola ręcznie.'}</Notice>}{result?.proposal&&<div className="draft-preview"><Badge tone="amber">Szkic, wymaga sprawdzenia</Badge><blockquote>{result.proposal.excerpt}</blockquote><p>{result.proposal.summary}</p><dl><dt>Element</dt><dd>{nameOf(subjects.find(s=>s.id===result.proposal.subjectId))}</dd><dt>Stan</dt><dd>{result.proposal.observedState||'Nie ustalono'}</dd><dt>Czas</dt><dd>{result.proposal.observedAt||'Nie ustalono'}</dd></dl><p className="muted">Brakujące pola: {(result.proposal.missingFields||[]).join(', ')||'Brak wskazanych przez model'}. Oryginał nie zostanie zmieniony.</p><Button onClick={()=>{onAdopt(result.proposal);setResult(null);}}>Sprawdziłem szkic, uzupełnij pola formularza</Button></div>}</details>;
}

export function PublicSourceImport({onDraft}:{onDraft:(draft:Entity)=>Promise<void>}){
  const{online,run,canManage}=useApp();const status=useIntegrationStatus();const[url,setUrl]=useState('');const[stored,setStored]=useState(false);const[consent,setConsent]=useState(false);const[result,setResult]=useState<Entity|null>(null);const[busy,setBusy]=useState(false);const enabled=online&&status?.publicSources?.enabled;
  return <Panel><SectionHeading title="Szkic z publicznego źródła" eyebrow="OPCJONALNY IMPORT" action={<Badge tone={enabled?'green':'neutral'}>{enabled?'Włączony':'Wyłączony'}</Badge>}/><p>Pobrana strona zachowuje adres, czas i fragment źródła. Pobranie nie uwierzytelnia informacji i nie publikuje procedury.</p><Field label="Adres publicznego źródła HTTPS" help={`Dozwolone domeny: ${(status?.publicSources?.allowedHosts||[]).join(', ')||'nie skonfigurowano'}`}><input type="url" value={url} onChange={e=>{setUrl(e.target.value);setConsent(false);}} placeholder="https://…"/></Field><label className="checkbox"><input type="checkbox" checked={consent} disabled={!enabled} onChange={e=>setConsent(e.target.checked)}/>Zgadzam się pobrać wybrany adres {status?.publicSources?.provider==='firecrawl'?'z użyciem zewnętrznego dostawcy Firecrawl':'przez serwer organizacji'}.</label><Button disabled={!enabled||!canManage||!consent||!url||busy} onClick={()=>{setBusy(true);run(async()=>{setStored(false);const received=await api('/api/sources/preview','POST',{url,consent:true});setResult(received);if(received.text){await onDraft(received);setStored(true);}}).finally(()=>setBusy(false));}}>{busy?'Pobieranie źródła…':'Pobierz szkic do sprawdzenia'}</Button>{!enabled&&<p className="muted">Import publiczny jest niedostępny. Użyj importu pliku lub wklej tekst dokumentu.</p>}{result?.text?<div className="draft-preview"><Notice>Źródło niezweryfikowane. Nie opublikowano żadnej procedury.</Notice><p>{result.url} · pobrano {timeOf(result.retrievedAt)} · {result.status}</p><pre>{result.text}</pre><div className="button-row">{stored?<p>Szkic zapisano lokalnie. Otworzysz go w lokalnych szkicach dokumentów.</p>:<Button onClick={()=>run(async()=>{await onDraft(result);setStored(true);})}>Ponów zapis szkicu dokumentu</Button>}<Button onClick={()=>download('most-szkic-zrodla.json',JSON.stringify(result,null,2))}>Eksport ze wskazaniem źródła</Button></div></div>:result&&<Notice>{result.message||'Nie udało się pobrać źródła. Dostępna jest ścieżka ręczna.'}</Notice>}</Panel>;
}
