import { useState, type FormEvent } from 'react';
import { FilePlus2, MessageSquareText, Paperclip, Plus, ShieldCheck } from 'lucide-react';
import { useApp } from './context';
import { arr, nameOf, timeOf, type Entity } from './types';
import { Badge, Button, Empty, Field, Modal, Notice, PageHeading, Panel, Status, Submit } from './ui';
import { db, fileHash } from './db';
import { AiExtractor } from './Integrations';
import { AssessmentDetails } from './AssessmentDetails';

export async function storeEvidence(scope: string, file: File) { if (!file.size || file.size > 5*1024*1024) throw new Error('Dowód musi mieć od 1 bajtu do 5 MB.');if(file.type&&!/^(application\/(pdf|json|octet-stream|vnd.openxmlformats-officedocument.wordprocessingml.document)|text\/(plain|csv)|image\/(png|jpeg|webp))$/.test(file.type))throw new Error('Obsługiwane dowody: PNG, JPEG, WebP, PDF, DOCX, JSON, CSV i TXT.');const hash=await fileHash(file);await db.files.put({id:hash,scope,blob:file,name:file.name,sha256:hash,status:'pending'});return hash; }
export function Observations() {
  const {snapshot,account,command,run,canManage,canEdit,queue}=useApp(); const[adding,setAdding]=useState(false);const[original,setOriginal]=useState('');const[subjectId,setSubjectId]=useState('');const[claimedState,setClaimedState]=useState('unknown');const[observedAt,setObservedAt]=useState(new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));const[busy,setBusy]=useState(false);const[assessing,setAssessing]=useState<Entity|null>(null); const pending=queue.filter(q=>q.command.type==='observation.create'&&q.status!=='accepted');const observations:Entity[]=[...arr(snapshot.observations).map(o=>({...o,local:false})),...pending.map(q=>({...q.command.payload,id:q.commandId,verificationStatus:'unverified',local:true,queueStatus:q.status}))]; const subjects=[...arr(snapshot.model.dependencies).filter(d=>d.kind==='leaf'),...arr(snapshot.model.resources)];
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=new FormData(e.currentTarget);await run(async()=>{const file=form.get('evidence') as File;const evidenceIds=file?.size?[await storeEvidence(account.scope,file)]:[];await command('observation.create',{id:crypto.randomUUID(),incidentId:snapshot.incident?.id||snapshot.incidents?.find(i=>i.status==='open')?.id,text:String(form.get('text')),source:String(form.get('source')),observedAt:new Date(String(form.get('observedAt'))).toISOString(),subjectId:String(form.get('subjectId')),claimedState:String(form.get('claimedState')),evidenceIds,kind:form.get('instruction')?'instruction':'observation'});setAdding(false);setOriginal('');});setBusy(false);}
  async function assess(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);await run(async()=>{await command('assessment.create',{incidentId:snapshot.incident?.id||snapshot.incidents?.[0]?.id,subjectId:assessing?.subjectId,state:String(f.get('state')),observationIds:[assessing?.id],reason:String(f.get('reason'))});setAssessing(null);});setBusy(false);}
  return <><PageHeading eyebrow="FAKTY I ŹRÓDŁA" title="Meldunki" action={<Button kind="primary" onClick={()=>setAdding(true)} disabled={!canEdit}><Plus size={17}/>Nowy meldunek</Button>}>Zachowaj oryginalną informację. Osobno oceń jej wiarygodność i wpływ na plan.</PageHeading><Notice>Niepotwierdzony meldunek nie zwiększa dostępnej puli zasobów. Polecenie w treści wiadomości pozostaje informacją, dopóki uprawniona osoba nie podejmie decyzji.</Notice>
  {observations.length?<div className="observation-list">{[...observations].reverse().map(o=><Panel key={o.id}><div className="observation-head"><div className="observation-icon"><MessageSquareText size={20}/></div><div><h3>{nameOf(subjects.find(s=>s.id===o.subjectId))}</h3><p>{o.source} · obserwacja {timeOf(o.observedAt)}</p></div><Status value={o.verificationStatus||o.status}/>{o.local&&<Badge tone="amber">Na tym urządzeniu</Badge>}</div><blockquote>{o.original||o.text}</blockquote><div className="observation-meta"><span>Stan w meldunku: <Status value={o.observedState||o.claimedState}/></span><span><Paperclip size={15}/>{(o.evidenceIds||[]).length?`${o.evidenceIds.length} załącznik(i)`:'Brak załączonego dowodu'}</span>{o.kind==='instruction'&&<Badge tone="amber">Treść zawiera polecenie</Badge>}</div>{(o.evidenceIds||[]).map((id:string)=>{const evidence=arr(snapshot.evidence).find(e=>e.id===id||e.sha256===id);return <p className="muted" key={id}>Dowód: {evidence?.filename||evidence?.name||id.slice(0,12)} · {evidence?.status==='complete'||evidence?.complete?'dostępny na serwerze':'kompletność niepotwierdzona'}</p>;})}{!o.local&&<AssessmentDetails observation={o}/>}
{canManage&&!o.local&&<Button onClick={()=>setAssessing(o)}><ShieldCheck size={16}/>Oceń i potwierdź stan</Button>}{!o.local&&canEdit&&(canManage||o.authorId===account.user.id)&&<Field label="Dołącz kolejny dowód"><input type="file" accept="image/*,.pdf,.txt,.json,.csv" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{const id=await storeEvidence(account.scope,file);await command('observation.attach',{observationId:o.id,evidenceIds:[id]});});}}/></Field>}{o.local&&<p className="muted">Serwer jeszcze nie przyjął meldunku. {o.queueStatus==='conflict'?'Wymaga rozstrzygnięcia w synchronizacji.':''}</p>}</Panel>)}</div>:<Panel><Empty title="Jeszcze nie zapisano meldunków" action={<Button onClick={()=>setAdding(true)}><FilePlus2 size={16}/>Dodaj pierwszy meldunek</Button>}>Zacznij od źródła, czasu i oryginalnej treści obserwacji.</Empty></Panel>}
  {adding&&<Modal title="Nowy meldunek" close={()=>setAdding(false)}><form onSubmit={add}><Field label="Oryginalna treść"><textarea name="text" value={original} onChange={e=>setOriginal(e.target.value)} rows={4} required maxLength={20000} placeholder="Co zaobserwowano? Zachowaj oryginalne brzmienie informacji."/></Field><div className="form-two"><Field label="Źródło informacji"><input name="source" required placeholder="Dyżurny, własna obserwacja, radio…"/></Field><Field label="Czas obserwacji"><input name="observedAt" type="datetime-local" required value={observedAt} onChange={e=>setObservedAt(e.target.value)}/></Field></div><Field label="Element, którego dotyczy"><select name="subjectId" required value={subjectId||subjects[0]?.id} onChange={e=>setSubjectId(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Stan opisany w meldunku"><select name="claimedState" value={claimedState} onChange={e=>setClaimedState(e.target.value)}><option value="unknown">Nieustalony</option><option value="unavailable">Niedostępny</option><option value="available">Dostępny</option></select></Field><label className="checkbox"><input type="checkbox" name="instruction"/>Wiadomość zawiera polecenie lub prośbę o zmianę przydziału</label><Field label="Dowód (opcjonalny)" help="Możesz dodać dowód później. Brak pliku pozostanie widoczny."><input type="file" name="evidence" accept="image/*,.pdf,.txt,.json,.csv"/></Field><Notice>Zapis nie potwierdza prawdziwości meldunku ani upoważnienia do wykonania polecenia.</Notice><AiExtractor text={original} subjects={subjects} onAdopt={proposal=>{if(proposal.subjectId)setSubjectId(proposal.subjectId);if(proposal.observedState)setClaimedState(proposal.observedState);if(proposal.observedAt){const date=new Date(proposal.observedAt);setObservedAt(new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16));}}}/><Submit busy={busy}>Zapisz meldunek</Submit></form></Modal>}
  {assessing&&<Modal title="Ocena meldunku" close={()=>setAssessing(null)}><blockquote>{assessing.original||assessing.text}</blockquote><form onSubmit={assess}><Field label="Potwierdzony stan"><select name="state" defaultValue={assessing.observedState||assessing.claimedState||'unknown'}><option value="unknown">Nieustalony</option><option value="available">Dostępny</option><option value="unavailable">Niedostępny</option></select></Field><Field label="Przesłanki i sposób sprawdzenia"><textarea name="reason" required minLength={10} rows={4}/></Field><Notice>Zmiana istotnych przesłanek może unieważnić plan i zablokować rozpoczęcie powiązanych zadań. Sprzeczne oryginały pozostaną w historii.</Notice><Submit busy={busy}>Zapisz ocenę</Submit></form></Modal>}
  </>;
}


