import { ArrowRight, ArrowUpRight, CircleCheck, ClipboardList, Droplets, FileCheck2, LifeBuoy, Radio, ShieldAlert, Timer, Waypoints, ZapOff } from 'lucide-react';
import { useApp } from './context';
import { arr, nameOf, stateLabel, timeOf, type Entity } from './types';
import { Badge, Button, Empty, LinkButton, Notice, PageHeading, Panel, SectionHeading, Status } from './ui';

export function currentPlan(snapshot: Entity) { const plans = arr(snapshot.plans); return [...plans].reverse().find(p => p.approvalStatus === 'approved' || p.status === 'approved') || plans.at(-1); }
export function allActions(snapshot: Entity) { const actions = arr(snapshot.actions); return actions.length ? actions : arr(currentPlan(snapshot)?.actions); }
export function Overview() {
  const { snapshot, drafts, navigate, queue, canManage } = useApp(); const model = snapshot.model; const services = arr(model.services); const plan = currentPlan(snapshot); const proposed = drafts.at(-1)?.payload?.plan; const prediction = plan || proposed;
  const actions = allActions(snapshot); const pendingActions = actions.filter(a => !['completed','cancelled'].includes(a.status));
  const verifiedServices = services.filter(s => arr(snapshot.verifications).some(v => { const action = actions.find(a => a.id === v.actionId); return action?.serviceId === s.id && v.outcome === 'passed' && !v.local && v.current !== false && !v.invalidatedAt && new Date(v.validUntil).getTime() > Date.now(); }));
  const observations = arr(snapshot.observations); const unconfirmed = observations.filter(o => !['confirmed','rejected'].includes(o.verificationStatus || o.status)); const icons = [LifeBuoy, Radio, Droplets];
  return <><PageHeading eyebrow="OBRAZ SYTUACJI" title="Zaplanuj pracę usług podczas awarii" action={<Button kind="primary" onClick={() => navigate('plans')}>Wyznacz plan<ArrowRight size={17}/></Button>}>Najważniejsze usługi, dostępne zasoby i kolejny krok Twojego zespołu.</PageHeading>
    <div className="summary-strip"><div><span className="metric-label">POTWIERDZONE USŁUGI</span><strong>{verifiedServices.length}<span> / {services.length}</span></strong><small><CircleCheck size={13}/> Wynik ważnych testów działania</small></div><div><span className="metric-label">PROGNOZA W MODELU</span><strong>{prediction?.metrics?.simultaneousMinimumFromMinute != null ? `${prediction.metrics.simultaneousMinimumFromMinute}` : '—'}<span> min</span></strong><small><Timer size={13}/> Do jednoczesnego osiągnięcia minimów</small></div><div><span className="metric-label">DO SPRAWDZENIA</span><strong>{arr(model.uncertainties).length + unconfirmed.length}</strong><small><ShieldAlert size={13}/> Pytania i nieocenione meldunki</small></div><div><span className="metric-label">DZIAŁANIA W TOKU</span><strong>{pendingActions.length.toString().padStart(2,'0')}</strong><small><ClipboardList size={13}/> {queue.filter(q => q.status !== 'accepted').length} zmian czeka na uzgodnienie</small></div></div>
    <SectionHeading title="Stan usług" eyebrow="NAJPIERW REZULTAT" action={<LinkButton onClick={() => navigate('graph')}>Zobacz zależności</LinkButton>}>Prognoza planu i wynik obserwacji są oceniane osobno.</SectionHeading>
    <div className="service-grid">{services.map((service, index) => {
      const Icon = icons[index % icons.length]; const timeline = arr(prediction?.timeline).find(t => t.serviceId === service.id); const action = arr(prediction?.actions).find(a => a.serviceId === service.id); const mode = arr(model.modes).find(m => m.id === action?.modeId); const verified = verifiedServices.some(s => s.id === service.id); const latestTest = [...arr(snapshot.verifications)].reverse().find(v => actions.find(a => a.id === v.actionId)?.serviceId === service.id);
      return <Panel className="service-card" key={service.id}><div className="service-top"><div className={`service-icon icon-${index}`}><Icon size={24}/></div><Badge tone={verified ? 'green' : 'amber'}>{verified ? 'Wynik sprawdzony' : 'Wymaga potwierdzenia'}</Badge></div><h3>{service.name}</h3><p className="service-outcome">{service.outcome}</p><div className="service-minimum"><span>WYMAGANE MINIMUM</span><strong>{service.minimum}<small> {service.unit}</small></strong></div><div className="service-detail"><span>Przewidywany tryb</span><strong>{mode?.name || 'Plan nie został wyznaczony'}</strong></div><div className="service-detail"><span>Minimum w modelu</span><strong>{timeline?.firstMinimumMinute != null ? `od ${timeline.firstMinimumMinute}. minuty` : 'Nie ustalono'}</strong></div><div className="service-detail"><span>Ostatni test</span><strong>{latestTest ? stateLabel(latestTest.outcome) : 'Brak testu działania'}</strong></div><button className="service-open" onClick={() => navigate('tasks')}>Procedura i potwierdzenie<ArrowUpRight size={17}/></button></Panel>;
    })}</div>
    <div className="overview-bottom"><Panel><SectionHeading eyebrow="REAKCJA" title="Działania teraz" action={<Badge>{pendingActions.length}</Badge>}/>{pendingActions.length ? pendingActions.slice(0,3).map((action,index) => <button className="action-row" key={action.id} onClick={() => navigate('tasks')}><span className="step-number">{String(index+1).padStart(2,'0')}</span><span><strong>{nameOf(arr(model.modes).find(m => m.id === action.modeId))}</strong><small>{nameOf(services.find(s => s.id === action.serviceId))} · {action.readyMinute - action.startMinute} min przygotowania</small></span><Status value={action.status}/><ArrowRight size={17}/></button>) : <Empty title="Zacznij od wykonalnego planu" action={<Button onClick={() => navigate('plans')}>Przejdź do planowania<ArrowRight size={15}/></Button>}>Wspólny przydział powstanie po zatwierdzeniu przez koordynatora.</Empty>}</Panel>
    <Panel className="check-panel"><SectionHeading eyebrow="MNIEJ NIEPEWNOŚCI" title="Co sprawdzić najpierw" action={<ShieldAlert size={23}/>}/>{arr(model.uncertainties).slice(0,2).map((u,index) => <div className="question-row" key={u.id}><span className="question-index">{index+1}</span><div><h3>{u.question}</h3><p>{u.contact} · ok. {u.verificationMinutes} min</p></div></div>)}<LinkButton onClick={() => navigate('checks')}>Porównaj wpływ odpowiedzi</LinkButton></Panel></div>
    <div className="insight"><div className="insight-icon"><Waypoints size={23}/></div><div><strong>Sprawdź, czy oba łącza zależą od jednego routera.</strong><p>Sprawdź wspólne zasilanie i router. Awaria wspólnego elementu może wyłączyć światłowód oraz LTE.</p></div><Button onClick={() => navigate('graph')}>Wyjaśnij przyczynę<ArrowUpRight size={16}/></Button></div>
  </>;
}

export function Timeline({ plan, model }: { plan: Entity; model: Entity }) { const horizon = plan.horizonMinutes || model.horizonMinutes || 120; return <div className="timeline"><div className="timeline-ruler"><span>USŁUGA / TRYB</span><div>{[0, .25, .5, .75, 1].map(p => <span key={p}>{Math.round(horizon*p)} min</span>)}</div></div>{arr(plan.timeline).map(t => <div className="timeline-row" key={t.serviceId}><div><strong>{nameOf(arr(model.services).find(s => s.id === t.serviceId))}</strong><small>{t.minimumMinutes} min na minimum · przerwa {t.outageMinutes} min</small></div><div className="timeline-track">{arr(t.intervals).map((i,index) => <div key={index} className={`timeline-segment ${i.meetsMinimum ? 'meets' : 'outage'}`} style={{left:`${i.startMinute/horizon*100}%`,width:`${(i.endMinute-i.startMinute)/horizon*100}%`}} title={`${i.startMinute}–${i.endMinute} min: ${i.meetsMinimum ? 'osiąga' : 'poniżej'} minimum (${i.level})`}/>)}</div></div>)}<div className="timeline-legend"><span><i className="legend-green"/> Osiąga minimum w modelu</span><span><i className="legend-amber"/> Poniżej minimum / przygotowanie</span></div></div>; }
