import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Check, ClipboardCheck, Download, Edit3, FileUp, Plus, ShieldCheck, Users, Wrench } from 'lucide-react';
import { useApp } from './context';
import { arr, nameOf, roleLabel, timeOf, type Entity } from './types';
import { Badge, Button, Empty, Field, Modal, Notice, PageHeading, Panel, SectionHeading, Status, Submit } from './ui';
import { api } from './api';
import { download } from './db';
import { procedureCards } from './cards';
import { Recovery } from './Recovery';
import { ReadinessTrial } from './ReadinessTrial';
import { PublicSourceImport } from './Integrations';
import { DocumentDraftEditor, DocumentDraftLibrary, useDocumentDrafts } from './DocumentDrafts';
import { ReadinessStatus } from './ReadinessStatus';
import { ModelValidationNotice } from './ModelValidationNotice';

export function Readiness() { const{snapshot,account,command,run,canManage,online,refresh,inform}=useApp();const model=snapshot.model;const[tab,setTab]=useState('services');const[editing,setEditing]=useState<Entity|null>(null);const[json,setJson]=useState<string|null>(null);const[importing,setImporting]=useState(false);const[preview,setPreview]=useState<Entity|null>(null);const[importText,setImportText]=useState('');const[busy,setBusy]=useState(false);const[userForm,setUserForm]=useState(false);const[scopeForm,setScopeForm]=useState(false);const documentDrafts=useDocumentDrafts(account.scope);const docDraft=documentDrafts.selected;const[csvEntity,setCsvEntity]=useState('services');
  const[importBusy,setImportBusy]=useState(false);const[importPhase,setImportPhase]=useState('');const[importError,setImportError]=useState('');const[importFile,setImportFile]=useState<File|null>(null);const importController=useRef<AbortController|null>(null);
  useEffect(()=>()=>{importController.current?.abort();importController.current=null;},[]);
  async function importOperation(phase:string,operation:(signal:AbortSignal)=>Promise<void>){
    if(importController.current)return;
    const controller=new AbortController();importController.current=controller;setImportBusy(true);setImportError('');setImportPhase(phase);
    try{await operation(controller.signal);}
    catch(error){if(importController.current===controller)setImportError(controller.signal.aborted?`Przerwano oczekiwanie. Wybrany plik i dane formularza pozostają zachowane.${phase.startsWith('Zatwierdzanie')?' Sprawdź bieżącą wersję modelu przed ponowieniem zatwierdzenia.':''}`:error instanceof Error?error.message:String(error));}
    finally{if(importController.current===controller){importController.current=null;setImportBusy(false);setImportPhase('');}}
  }
  function closeImport(){importController.current?.abort();setImporting(false);}
  const issues=arr(model.services).flatMap(s=>{const modes=arr(model.modes).filter(m=>m.serviceId===s.id);return[...(!s.ownerId?[`${s.name}: brak właściciela`]:[]),...(!modes.length?[`${s.name}: brak trybu działania`]:[]),...modes.filter(m=>!m.approved||!arr(model.procedures).some(p=>p.id===m.procedureId&&p.approved)||!arr(model.verificationContracts).some(c=>c.id===m.verificationContractId)).map(m=>`${m.name}: brak zatwierdzonego trybu, procedury lub kontraktu testu`)]}).concat(arr(snapshot.modelValidation?.blockedFragments).filter(f=>f.kind==='mode').map(f=>`${nameOf(arr(model.modes).find(m=>m.id===f.id))}: wykluczony z planowania (${(f.reasons||[]).join('; ')})`),snapshot.modelValidation?.valid===false?['Błędy całego modelu blokują obliczenia i zatwierdzenie.']:[]);
  async function serviceSave(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const next=structuredClone(model);const service={...editing,id:editing?.id||crypto.randomUUID(),name:f.get('name'),outcome:f.get('outcome'),unit:f.get('unit'),minimum:Number(f.get('minimum')),priority:Number(f.get('priority')),weight:Number(f.get('weight')),toleratedOutageMinutes:Number(f.get('toleratedOutageMinutes')),ownerId:f.get('ownerId'),deputyId:f.get('deputyId'),location:f.get('location'),version:(editing?.version||0)+1,provenance:{...editing?.provenance,source:String(f.get('parameterSource')),checkedAt:new Date(String(f.get('parameterCheckedAt'))).toISOString(),synthetic:Boolean(model.synthetic)}};const index=next.services.findIndex((s:Entity)=>s.id===service.id);if(index<0)next.services.push(service);else next.services[index]=service;setBusy(true);await run(async()=>{await command('model.replace',{model:next});setEditing(null);});setBusy(false);}
  async function previewImport(){await importOperation('Sprawdzanie danych i przygotowywanie podglądu…',async signal=>{const isJson=importText.trim().startsWith('{')||importText.trim().startsWith('[');const data=await api('/api/import/preview','POST',{format:isJson?'json':'csv',content:importText,model:isJson?JSON.parse(importText):undefined,entity:csvEntity},{signal});signal.throwIfAborted();setPreview(data);});}
  async function documentImport(file:File){await importOperation(`Przetwarzanie pliku ${file.name}… Pierwszy odczyt dokumentu może potrwać do 60 s.`,async signal=>{
    setImportFile(file);setPreview(null);setImportText('');documentDrafts.clear();if(file.size>5*1024*1024)throw new Error('Dokument przekracza 5 MB.');
    if(/\.(json|csv)$/i.test(file.name)){const text=await file.text();signal.throwIfAborted();setImportText(text);return;}
    const bytes=new Uint8Array(await file.arrayBuffer());signal.throwIfAborted();let binary='';for(const b of bytes)binary+=String.fromCharCode(b);
    const response=await api('/api/import/preview','POST',{filename:file.name,format:file.name.split('.').at(-1)?.toLowerCase(),base64:btoa(binary)},{timeoutMs:60000,signal});signal.throwIfAborted();setImportPhase('Zapisywanie szkicu i odniesień do źródła na tym urządzeniu…');await documentDrafts.receive(response);
  });}
  return <><PageHeading eyebrow="PRZYGOTOWANIE ORGANIZACJI" title="Gotowość do działania" action={<Button disabled={!canManage} onClick={()=>setImporting(true)}><FileUp size={17}/>Importuj dane</Button>}>Właściciele, minima, zatwierdzone procedury i aktualne parametry tworzą podstawę wiarygodnego planu.</PageHeading><Recovery/><ReadinessStatus/><DocumentDraftLibrary drafts={documentDrafts.drafts} error={documentDrafts.error} onOpen={draft=>{documentDrafts.select(draft);setImporting(true);}}/><div className="readiness-summary"><Panel><ShieldCheck size={25}/><div><strong>{arr(model.services).length}</strong><span>usługi w modelu</span></div></Panel><Panel><ClipboardCheck size={25}/><div><strong>{arr(model.procedures).filter(p=>p.approved).length} / {arr(model.procedures).length}</strong><span>zatwierdzone procedury</span></div></Panel><Panel><Wrench size={25}/><div><strong>{issues.length}</strong><span>braki do uzupełnienia</span></div></Panel></div>{issues.length?<Notice tone="red">{issues.map((issue,index)=><p key={index}>{issue}</p>)}</Notice>:<Notice tone="green">Każda usługa ma właściciela, tryb, zatwierdzoną procedurę i kontrakt testu. Gotowość operacyjna wymaga jeszcze prób oraz odbioru danych przez właścicieli.</Notice>}
  <div className="tabs" role="tablist" aria-label="Obszary gotowości">{[['services','Usługi'],['resources','Zasoby'],['procedures','Procedury i testy'],['accounts','Konta i lokalne pule']].map(([id,label])=><button role="tab" id={`readiness-tab-${id}`} aria-controls="readiness-content" tabIndex={tab===id?0:-1} onKeyDown={e=>{const tabs=['services','resources','procedures','accounts'];const index=tabs.indexOf(tab);const next=e.key==='ArrowRight'?tabs[(index+1)%tabs.length]:e.key==='ArrowLeft'?tabs[(index+tabs.length-1)%tabs.length]:e.key==='Home'?tabs[0]:e.key==='End'?tabs.at(-1):null;if(next){e.preventDefault();setTab(next);document.getElementById(`readiness-tab-${next}`)?.focus();}}} aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
  <div id="readiness-content" role="tabpanel" aria-labelledby={`readiness-tab-${tab}`}>
  {tab==='services'&&<Panel><SectionHeading title="Kontrakty usług" action={<Button disabled={!canManage} onClick={()=>setEditing({})}><Plus size={16}/>Dodaj usługę</Button>}/><div className="table-scroll"><table><thead><tr><th>Usługa</th><th>Minimum</th><th>Priorytet</th><th>Tolerowana przerwa</th><th>Właściciel</th><th>Zmiana</th></tr></thead><tbody>{arr(model.services).map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.outcome}</small></td><td>{s.minimum} {s.unit}</td><td>Klasa {s.priority}, waga {s.weight}</td><td>{s.toleratedOutageMinutes} min</td><td>{nameOf(arr(snapshot.users).find(u=>u.id===s.ownerId))}</td><td><Button disabled={!canManage} kind="icon" aria-label={`Edytuj ${s.name}`} onClick={()=>setEditing(s)}><Edit3 size={17}/></Button></td></tr>)}</tbody></table></div><div className="button-row"><Button disabled={!canManage} onClick={()=>setJson(JSON.stringify(model,null,2))}>Edytuj pełny model JSON</Button><Button onClick={()=>download('most-model.json',JSON.stringify(model,null,2))}><Download size={16}/>Eksport modelu</Button></div></Panel>}
  {tab==='resources'&&<Panel><SectionHeading title="Dostępność i fizyczny stan zasobów"/><div className="table-scroll"><table><thead><tr><th>Zasób</th><th>Dostępność</th><th>Ilość</th><th>Kompetencje / zgodność</th><th>Źródło i sprawdzenie</th><th>Działanie</th></tr></thead><tbody>{arr(model.resources).map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.location}</small></td><td><Status value={r.state}/>{r.occupied&&<Badge tone="amber">Zajęty fizycznie</Badge>}</td><td>{r.quantity} {r.unit}</td><td>{[...(r.skills||[]),...(r.tags||[])].join(', ')||'Nie dotyczy'}</td><td>{r.provenance?.source}<small>{timeOf(r.provenance?.checkedAt)}</small></td><td><div className="stack"><select aria-label={`Dostępność ${r.name}`} disabled={!canManage} value={r.state} onChange={e=>run(()=>command('resource.update',{resourceId:r.id,state:e.target.value,reason:'Stan potwierdzony przez koordynatora w widoku zasobów.'}))}><option value="available">Dostępny</option><option value="unavailable">Niedostępny</option><option value="unknown">Niepotwierdzony</option></select>{r.type==='equipment'&&<Button disabled={!canManage} onClick={()=>run(()=>command('resource.release',{resourceId:r.id,physicalConfirmed:true,notes:'Potwierdzono fizyczny zwrot zasobu w widoku zasobów.'}))}>Potwierdź fizyczny zwrot</Button>}</div></td></tr>)}</tbody></table></div><Notice>Upływ czasu rezerwacji nie potwierdza zwrotu. Przycisku zwolnienia użyj dopiero po sprawdzeniu rzeczywistego położenia i stanu sprzętu.</Notice></Panel>}
  {tab==='procedures'&&<><ReadinessTrial/><PublicSourceImport onDraft={async draft=>{await documentDrafts.receive(draft);setImporting(true);}}/><div className="procedure-grid">{arr(model.procedures).map(p=><Panel key={p.id}><SectionHeading title={p.title} action={<Badge tone={p.approved?'green':'amber'}>{p.approved?'Zatwierdzona':'Szkic'} · v{p.version}</Badge>}/><ol>{(p.steps||[]).map((step:string,index:number)=><li key={index}>{step}</li>)}</ol><Notice>{p.safetyNote}</Notice><p className="muted">Źródło: {p.provenance?.source}. Sprawdzone {timeOf(p.provenance?.checkedAt)}.</p>{arr(model.modes).filter(m=>m.procedureId===p.id).map(m=>{const contract=arr(model.verificationContracts).find(c=>c.id===m.verificationContractId);return <div className="contract-block" key={m.id}><strong>{contract?.title}</strong><p>{contract?.expectedResult}</p><small>Kontrakt v{contract?.version} · ważność {contract?.validityMinutes} min · {contract?.simulated?'symulacja':'test rzeczywistej czynności'}</small></div>;})}<Button onClick={()=>download(`most-procedura-${p.id}.html`,procedureCards(model,p.id),'text/html')}>Karta do druku</Button></Panel>)}</div></>}
  {tab==='accounts'&&<><Panel><SectionHeading title="Konta organizacji" action={<Button disabled={account.user.role!=='administrator'||!online} onClick={()=>setUserForm(true)}><Plus size={16}/>Nowe konto</Button>}/><div className="table-scroll"><table><thead><tr><th>Osoba</th><th>Login</th><th>Rola</th><th>Status</th></tr></thead><tbody>{arr(snapshot.users).map(u=><tr key={u.id}><td>{u.displayName}</td><td>{u.username}</td><td>{account.user.role==='administrator'&&u.id!==account.user.id?<select aria-label={`Rola ${u.displayName}`} value={u.role} disabled={!online} onChange={e=>run(async()=>{await api(`/api/users/${encodeURIComponent(u.id)}`,'PATCH',{role:e.target.value});await refresh();})}>{['administrator','coordinator','owner','operator','observer'].map(role=><option value={role} key={role}>{roleLabel(role)}</option>)}</select>:roleLabel(u.role)}</td><td>{u.active===false?'Wyłączone':'Aktywne'}{account.user.role==='administrator'&&u.id!==account.user.id&&<Button disabled={!online} onClick={()=>run(async()=>{await api(`/api/users/${encodeURIComponent(u.id)}`,'PATCH',{active:u.active===false});await refresh();})}>{u.active===false?'Przywróć dostęp':'Cofnij dostęp'}</Button>}</td></tr>)}</tbody></table></div></Panel><Panel><SectionHeading title="Wcześniej przyznane lokalne pule" action={<Button disabled={!['administrator','coordinator'].includes(account.user.role)} onClick={()=>setScopeForm(true)}><Plus size={16}/>Przyznaj pulę</Button>}/><p>Rozłączne pule ograniczają lokalne przeplanowanie do zatwierdzonych zasobów, trybów, osoby i czasu.</p>{[...arr(snapshot.allocationScopes)].map(s=><div className="scope-card" key={s.id}><strong>{nameOf(arr(snapshot.users).find(u=>u.id===s.authorizedUserId))}</strong><p>{(s.resourceIds||[]).map((id:string)=>nameOf(arr(model.resources).find(r=>r.id===id))).join(', ')}</p><small>{timeOf(s.validFrom)} do {timeOf(s.validUntil)} · {s.allowLocalReplanning?'Lokalne przeplanowanie dozwolone':'Bez zmiany planu'}</small>{s.revokedAt?<p>Pula została zamknięta.</p>:['administrator','coordinator'].includes(account.user.role)&&<div className="button-row"><Button onClick={()=>run(()=>command('scope.release',{scopeId:s.id,physicalConfirmed:true}))}>Potwierdź fizyczny zwrot i zamknij pulę</Button></div>}</div>)}</Panel></>}
  </div>
  {editing&&<Modal title={editing.id?'Edytuj kontrakt usługi':'Nowa usługa'} close={()=>setEditing(null)}><form onSubmit={serviceSave}><Field label="Nazwa usługi"><input name="name" required defaultValue={editing.name}/></Field><Field label="Rezultat dla odbiorcy"><textarea name="outcome" required defaultValue={editing.outcome}/></Field><div className="form-two"><Field label="Minimum"><input name="minimum" type="number" min="0" step="any" required defaultValue={editing.minimum||1}/></Field><Field label="Jednostka"><input name="unit" required defaultValue={editing.unit}/></Field><Field label="Klasa priorytetu (1 najwyższa)"><input name="priority" type="number" min="1" max="10" defaultValue={editing.priority||1}/></Field><Field label="Waga w klasie"><input name="weight" type="number" min="1" defaultValue={editing.weight||1}/></Field><Field label="Tolerowana przerwa (min)"><input name="toleratedOutageMinutes" type="number" min="0" defaultValue={editing.toleratedOutageMinutes||30}/></Field><Field label="Lokalizacja"><input name="location" required defaultValue={editing.location||'Punkt lokalny'}/></Field></div><Field label="Źródło parametrów usługi"><input name="parameterSource" required defaultValue={editing.provenance?.source}/></Field><Field label="Data sprawdzenia parametrów"><input name="parameterCheckedAt" type="datetime-local" step="1" required defaultValue={new Date((Date.parse(editing.provenance?.checkedAt)||Date.now())-new Date().getTimezoneOffset()*60000).toISOString().slice(0,19)}/></Field><Field label="Właściciel"><select name="ownerId" defaultValue={editing.ownerId}>{arr(snapshot.users).filter(u=>u.active!==false&&['administrator','coordinator','owner'].includes(u.role)).map(u=><option value={u.id} key={u.id}>{u.displayName}</option>)}</select></Field><Field label="Zastępstwo"><select name="deputyId" defaultValue={editing.deputyId}><option value="">Nie wskazano</option>{arr(snapshot.users).map(u=><option value={u.id} key={u.id}>{u.displayName}</option>)}</select></Field><Submit busy={busy}>Zapisz nową wersję</Submit></form></Modal>}
  {json!==null&&<Modal title="Model, zależności i procedury" wide close={()=>setJson(null)}><p>Zmiana tworzy nową wersję po kontroli serwera. Błędy jednostek lub całego modelu zablokują zmianę. Cykle i brakujące odwołania wyłączą wskazane fragmenty z planowania, z podaniem przyczyny.</p><textarea aria-label="Pełny model JSON" className="code-input" rows={22} value={json} onChange={e=>setJson(e.target.value)}/><Button kind="primary" onClick={()=>run(async()=>{await command('model.replace',{model:JSON.parse(json)});setJson(null);})}>Sprawdź i zatwierdź zmianę modelu</Button></Modal>}
  {importing&&<Modal title="Import i podgląd zmian" wide close={closeImport}>
    <Field label="Plik JSON / CSV lub dokument PDF / DOCX"><input type="file" accept=".json,.csv,.pdf,.docx,.txt" disabled={importBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void documentImport(file);}}/></Field>
    {importFile&&<p>Wybrany plik: <strong>{importFile.name}</strong></p>}
    {importBusy&&<div role="status" aria-live="polite"><p>{importPhase}</p><Button onClick={()=>importController.current?.abort()}>Przerwij oczekiwanie</Button></div>}
    {importError&&<Notice tone="red"><span role="alert">{importError}</span>{importFile&&!importBusy&&!docDraft&&<div className="button-row"><Button disabled={!online} onClick={()=>documentImport(importFile)}>Ponów odczyt wybranego pliku</Button></div>}</Notice>}
    {docDraft&&<DocumentDraftEditor draft={docDraft} status={documentDrafts.status} error={documentDrafts.error} onSave={documentDrafts.persist}/>}
    <Field label="Rodzaj obiektów w CSV"><select disabled={importBusy} value={csvEntity} onChange={e=>{setCsvEntity(e.target.value);setPreview(null);}}>{[['services','Usługi'],['resources','Zasoby'],['dependencies','Zależności'],['modes','Tryby'],['procedures','Procedury'],['verificationContracts','Kontrakty testów']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field>
    <Field label="Dane do importu"><textarea className="code-input" rows={12} disabled={importBusy} value={importText} onChange={e=>{setImportText(e.target.value);setPreview(null);}}/></Field>
    <Button disabled={importBusy||!online||!importText} onClick={previewImport}>Sprawdź i pokaż różnice</Button>
    {preview&&<><Notice tone={preview.validation?.valid===true?(preview.validation?.blockedFragments?.length?'amber':'green'):'red'}>{preview.validation?.valid===true?(preview.validation?.blockedFragments?.length?'Podgląd dopuszczony z wykluczeniami. Wskazane fragmenty nie będą używane do planowania.':'Podgląd przeszedł kontrolę. Zatwierdzenie zmieni model.'):'Podgląd zawiera błędy blokujące publikację modelu.'}</Notice><ModelValidationNotice validation={preview.validation} model={preview.model||model}/><pre className="preview-json">{JSON.stringify(preview,null,2)}</pre><Button kind="primary" disabled={importBusy||!online||preview.validation?.valid!==true} onClick={()=>importOperation('Zatwierdzanie podglądu na serwerze. Przerwanie oczekiwania nie cofa przyjętej zmiany.',async signal=>{await api('/api/import/commit','POST',{previewId:preview.previewId||preview.id,baseRevision:snapshot.revision},{signal});await refresh();signal.throwIfAborted();setImporting(false);setPreview(null);})}>Zatwierdź dokładnie ten podgląd</Button></>}
  </Modal>}
  {userForm&&<Modal title="Nowe lokalne konto" close={()=>setUserForm(false)}><form onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));run(async()=>{await api('/api/users','POST',data);await refresh();setUserForm(false);});}}><Field label="Imię i nazwisko / dyżur"><input name="displayName" required/></Field><Field label="Login"><input name="username" required minLength={3} autoComplete="off"/></Field><Field label="Hasło początkowe"><input name="password" type="password" required minLength={12} autoComplete="new-password"/></Field><Field label="Rola"><select name="role"><option value="operator">Wykonawca</option><option value="coordinator">Koordynator</option><option value="owner">Właściciel usługi</option><option value="observer">Obserwator</option><option value="administrator">Administrator</option></select></Field><Submit busy={false}>Utwórz konto</Submit></form></Modal>}
  {scopeForm&&<Modal title="Przyznaj lokalną pulę" wide close={()=>setScopeForm(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await command('scope.create',{id:crypto.randomUUID(),authorizedUserId:f.get('authorizedUserId'),resourceIds:f.getAll('resourceIds'),modeIds:f.getAll('modeIds'),validFrom:new Date().toISOString(),validUntil:new Date(Date.now()+Number(f.get('hours'))*3600000).toISOString(),allowLocalReplanning:true,conditions:[String(f.get('conditions'))]});setScopeForm(false);});}}><Field label="Osoba uprawniona"><select name="authorizedUserId">{arr(snapshot.users).filter(u=>u.active!==false&&u.role!=='observer').map(u=><option key={u.id} value={u.id}>{u.displayName}</option>)}</select></Field><Field label="Ważność (godziny)"><input name="hours" type="number" min="1" max="24" defaultValue="8"/></Field><h3>Zasoby</h3><div className="checkbox-grid">{arr(model.resources).map(r=><label className="checkbox" key={r.id}><input type="checkbox" name="resourceIds" value={r.id}/>{r.name}</label>)}</div><h3>Dozwolone tryby</h3>{arr(model.modes).filter(m=>m.approved).map(m=><label className="checkbox" key={m.id}><input type="checkbox" name="modeIds" value={m.id}/>{m.name}</label>)}<Field label="Warunki i ograniczenia"><textarea name="conditions" required rows={3}/></Field><Notice>Przyznanie puli oznacza ograniczenie prawa innych punktów do dysponowania tymi samymi zasobami. Pula musi być rozłączna z pozostałymi aktywnymi pulami.</Notice><Submit busy={false}>Zatwierdź lokalny zakres</Submit></form></Modal>}
  </>;
}
