import { useState } from 'react';
import { useApp } from './context';
import { arr, nameOf, timeOf } from './types';
import { Badge, Button, Field, Modal, Notice, Panel, SectionHeading } from './ui';

export function ReadinessTrial(){
  const {snapshot,command,run,canManage}=useApp();const[open,setOpen]=useState(false);const[modeId,setModeId]=useState('');
  const modes=arr(snapshot.model.modes);const selected=modes.find(m=>m.id===modeId)||modes[0];
  const results=arr(snapshot.verifications).filter(v=>v.current&&arr(snapshot.actions).some(a=>a.id===v.actionId&&a.modeId===selected?.id));
  const trials=arr(snapshot.readinessTrials);const excludedModes=new Set(arr(snapshot.modelValidation?.blockedFragments).filter(f=>f.kind==='mode').map(f=>f.id));
  return <Panel><SectionHeading title="Próby na znanym dobrym stanie" action={<Button disabled={!canManage||!modes.length} onClick={()=>setOpen(true)}>Zapisz próbę i pomiar przygotowania</Button>}/><p>Właściciel porównuje pomiar z kontraktem i zatwierdza źródła parametrów. Czas przygotowania danych jest osobnym pomiarem od czasu wykonania procedury.</p>{!trials.length?<Notice>Nie zapisano jeszcze odbioru próby. Po wykonaniu ćwiczenia i ważnego testu rezultatu zatwierdź pomiary z właścicielem usługi.</Notice>:<div className="table-scroll"><table><thead><tr><th>Tryb i wersja</th><th>Przygotowanie danych</th><th>Procedura</th><th>Poziom usługi</th><th>Aktualność</th><th>Odbiór</th></tr></thead><tbody>{[...trials].reverse().map(t=><tr key={t.id}><td>{nameOf(modes.find(m=>m.id===t.modeId))}<small>Model v{t.modelRevision}; procedura v{t.procedureVersion}</small></td><td>{t.preparationMinutes} min</td><td>{t.observedSetupMinutes} min</td><td>{t.measuredLevel} {arr(snapshot.model.services).find(s=>s.id===t.serviceId)?.unit}</td><td><Badge tone={!excludedModes.has(t.modeId)&&t.current===true&&(!t.verificationValidUntil||Date.parse(t.verificationValidUntil)>Date.now())&&!t.requiresModelReview?'green':'amber'}>{excludedModes.has(t.modeId)?'Tryb wykluczony z planowania':t.current!==true||t.verificationValidUntil&&Date.parse(t.verificationValidUntil)<=Date.now()?'Próba historyczna':t.requiresModelReview?'Parametry wymagają przeglądu':'Aktualna próba'}</Badge></td><td>{timeOf(t.approvedAt)}<small>{nameOf(arr(snapshot.users).find(u=>u.id===t.approvedBy))}</small></td></tr>)}</tbody></table></div>}
  {open&&<Modal title="Odbiór próby usługi" close={()=>setOpen(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(async()=>{await command('readiness.trial',{serviceId:selected.serviceId,modeId:selected.id,verificationId:String(f.get('verificationId')),preparationMinutes:Number(f.get('preparationMinutes')),observedSetupMinutes:Number(f.get('observedSetupMinutes')),measuredLevel:Number(f.get('measuredLevel')),source:String(f.get('source')),notes:String(f.get('notes')),knownGoodConfirmed:true});setOpen(false);});}}><Field label="Próbowany tryb"><select value={selected?.id} onChange={e=>setModeId(e.target.value)}>{modes.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field><Field label="Ważny pozytywny test z dowodem"><select name="verificationId" required>{results.length?results.map(v=><option key={v.id} value={v.id}>{timeOf(v.observedAt)}: {v.measuredValue} · {v.notes}</option>):<option value="">Najpierw wykonaj ćwiczenie i test</option>}</select></Field><div className="form-two"><Field label="Przygotowanie danych (min)"><input name="preparationMinutes" type="number" min="0" step="any" required/></Field><Field label="Zmierzony czas procedury (min)"><input name="observedSetupMinutes" type="number" min="0" step="any" required/></Field></div><Field label="Zmierzony poziom usługi"><input name="measuredLevel" type="number" min="0" step="any" required/></Field><Field label="Źródło i sposób pomiaru"><input name="source" required minLength={3}/></Field><Field label="Uwagi właściciela"><textarea name="notes" required minLength={5}/></Field><label className="checkbox"><input type="checkbox" required/>Właściciel sprawdził znany dobry stan, warunki próby i poprawność pomiaru.</label><Notice>Odbiór zapisuje pomiary i wersje. Zmiana parametrów modelu wymaga osobnej decyzji. Próba symulowana pozostaje symulacją.</Notice><Button kind="primary" type="submit" disabled={!results.length}>Zatwierdź pomiar próby</Button></form></Modal>}
  </Panel>;
}
