import { useState } from 'react';
import { useApp } from './context';
import { api } from './api';
import { arr, nameOf, roleLabel, type Entity } from './types';
import { Button, Field, Notice, Panel, SectionHeading } from './ui';

export function Recovery(){
  const {snapshot,account,command,run,online,refresh}=useApp();
  const [accountsChecked,setAccountsChecked]=useState(false);
  const [authorityStopped,setAuthorityStopped]=useState(false);
  const [checked,setChecked]=useState<Record<string,boolean>>({});
  const [values,setValues]=useState<Record<string,Entity>>({});
  const recovery=snapshot.recovery;
  if(!recovery?.isolated)return null;
  if(account.user.role!=='administrator')return <Notice tone="red">Instancja po odtworzeniu pozostaje odizolowana. Administrator musi przejrzeć konta, zasoby i lokalne pule przed przywróceniem przydziałów.</Notice>;
  const resources=arr(snapshot.model.resources).filter(r=>r.reconciliationRequired);
  const scopes=arr(snapshot.allocationScopes).filter(s=>s.reconciliationRequired&&!s.revokedAt);
  return <Panel><SectionHeading eyebrow="ODTWORZENIE KOPII" title="Przegląd przed wznowieniem przydziałów"/><Notice tone="red">Ta instancja nie może wydawać przydziałów. Dane kopii opisują dawny stan. Nie uruchamiaj równocześnie dwóch serwerów dysponujących tymi samymi zasobami.</Notice>
    <h3>1. Aktualne konta i role</h3><div className="table-scroll"><table><thead><tr><th>Osoba</th><th>Rola</th><th>Stan</th><th>Działanie</th></tr></thead><tbody>{arr(snapshot.users).map(user=><tr key={user.id}><td>{user.displayName}</td><td>{roleLabel(user.role)}</td><td>{user.active?'Aktywne':'Wyłączone'}</td><td><Button disabled={!online||user.id===account.user.id} onClick={()=>run(async()=>{await api(`/api/users/${encodeURIComponent(user.id)}`,'PATCH',{active:!user.active});await refresh();})}>{user.active?'Wyłącz cofnięte konto':'Przywróć sprawdzone konto'}</Button></td></tr>)}</tbody></table></div>
    {recovery.accountsReviewed?<Notice tone="green">Przegląd kont zapisano.</Notice>:<><label className="checkbox"><input type="checkbox" checked={accountsChecked} onChange={e=>setAccountsChecked(e.target.checked)}/>Porównano wszystkie konta i role z bieżącymi uprawnieniami organizacji.</label><Button disabled={!online||!accountsChecked} onClick={()=>run(()=>command('recovery.review_accounts',{confirmed:true}))}>Potwierdź przegląd kont</Button></>}
    <h3>2. Zasoby, zajęcie i rzeczywiste zapasy</h3>{resources.map(resource=>{const val=values[resource.id]||{};return <form key={resource.id} onSubmit={event=>{event.preventDefault();run(()=>command('resource.reconcile',{resourceId:resource.id,physicalConfirmed:true,state:val.state||'unknown',quantity:Number(val.quantity??resource.quantity),occupied:Boolean(val.occupied)}));}}><h4>{resource.name}</h4><div className="form-two"><Field label={`Aktualny stan: ${resource.name}`}><select value={val.state||'unknown'} onChange={e=>setValues(v=>({...v,[resource.id]:{...val,state:e.target.value}}))}><option value="unknown">Nieustalony, nie przydzielaj</option><option value="available">Sprawdzony i dostępny</option><option value="unavailable">Niedostępny</option></select></Field><Field label={`Rzeczywista ilość (${resource.unit}): ${resource.name}`}><input type="number" min="0" step="any" required value={val.quantity??resource.quantity} onChange={e=>setValues(v=>({...v,[resource.id]:{...val,quantity:e.target.value}}))}/></Field></div><label className="checkbox"><input type="checkbox" checked={Boolean(val.occupied)} onChange={e=>setValues(v=>({...v,[resource.id]:{...val,occupied:e.target.checked}}))}/>Zasób jest nadal fizycznie zajęty.</label><label className="checkbox"><input type="checkbox" checked={Boolean(checked[resource.id])} onChange={e=>setChecked(c=>({...c,[resource.id]:e.target.checked}))}/>Potwierdzono fizyczny stan i aktualną ilość tego zasobu z odpowiedzialną osobą.</label><Button type="submit" disabled={!online||!checked[resource.id]}>Zapisz uzgodnienie: {resource.name}</Button></form>;})}{!resources.length&&<Notice tone="green">Każdy zasób ma zapisane uzgodnienie.</Notice>}
    <h3>3. Pule przekazane urządzeniom</h3>{scopes.map(scope=><div key={scope.id}><p>{nameOf(arr(snapshot.users).find(u=>u.id===scope.authorizedUserId))}: {scope.resourceIds.map((id:string)=>nameOf(arr(snapshot.model.resources).find(r=>r.id===id))).join(', ')}</p><label className="checkbox"><input type="checkbox" checked={Boolean(checked[scope.id])} onChange={e=>setChecked(c=>({...c,[scope.id]:e.target.checked}))}/>Uzgodniono z dysponentem zakres puli i skutki pracy offline.</label><div className="button-row"><Button disabled={!online||!checked[scope.id]||resources.length>0} onClick={()=>run(()=>command('scope.reconcile',{scopeId:scope.id,physicalConfirmed:true,remainsActive:true}))}>Pula nadal obowiązuje</Button><Button disabled={!online||!checked[scope.id]||resources.length>0} onClick={()=>run(()=>command('scope.reconcile',{scopeId:scope.id,physicalConfirmed:true,remainsActive:false}))}>Zamknij uzgodnioną pulę</Button></div></div>)}{!scopes.length&&<p>Brak pul wymagających dalszego uzgodnienia.</p>}
    <h3>4. Jeden serwer uprawniony do przydziałów</h3><label className="checkbox"><input type="checkbox" checked={authorityStopped} onChange={e=>setAuthorityStopped(e.target.checked)}/>Sprawdzono, że stary serwer jest wyłączony i nie może wydawać przydziałów.</label><Button kind="primary" disabled={!online||!authorityStopped||!recovery.accountsReviewed||!recovery.resourcesReconciled||scopes.length>0} onClick={()=>run(()=>command('recovery.promote',{oldAuthorityDisabled:true}))}>Wznów przydziały na tej instancji</Button>
  </Panel>;
}
