export type Entity = Record<string, any>;
export interface User { id: string; username: string; displayName: string; role: string; organizationId: string; }
export interface Snapshot { serverEpoch: string; serverSeq: number; revision: number; organizationId: string; model: Entity; incidents: Entity[]; observations: Entity[]; assessments: Entity[]; plans: Entity[]; actions: Entity[]; verifications: Entity[]; allocations: Entity[]; allocationScopes: Entity[]; evidence: Entity[]; users: User[]; [key: string]: any; }
export interface Command { commandId: string; deviceId: string; organizationId: string; baseRevision: number; serverEpoch: string; dependsOn: string[]; type: string; schemaVersion: 1; payload: Entity; }
export interface Outbox { commandId: string; scope: string; command: Command; status: 'pending'|'accepted'|'conflict'|'rejected'|'waiting'; createdAt: string; result?: Entity; }
export interface Account { scope: string; user: User; csrfToken: string; offlineUntil: string; serverEpoch: string; lastServerTime: number; lastLocalTime: number; lastObservedLocalTime?: number; }
export interface StoredSnapshot { scope: string; snapshot: Snapshot; savedAt: string; }
export const arr = (value: any): Entity[] => Array.isArray(value) ? value : value && typeof value === 'object' ? Object.values(value) : [];
export const nameOf = (x: Entity | undefined) => x?.name || x?.title || x?.label || x?.displayName || x?.id || 'Nieokreślono';
export const timeOf = (s: any) => s ? new Date(s).toLocaleString('pl-PL', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : 'Brak zapisu';
export const stateLabel = (s: string | undefined) => ({available:'Dostępny',unavailable:'Niedostępny',unknown:'Nieustalony',confirmed:'Potwierdzony',verified:'Sprawdzony',unverified:'Niezweryfikowany',pending:'Oczekuje',accepted:'Przyjęto',approved:'Zatwierdzony',proposed:'Propozycja',draft:'Szkic',conflict:'Konflikt',rejected:'Odrzucono',waiting:'Czeka na poprzednika',completed:'Wykonano',in_progress:'W toku',started:'W toku',ready:'Gotowy',passed:'Spełniono',failed:'Nie spełniono',inconclusive:'Nie ustalono',skipped:'Pominięto',optimal:'Optimum w modelu',feasible:'Wykonalny',infeasible:'Niewykonalny',no_solution:'Nie znaleziono planu',invalid_model:'Błędny model',needs_review:'Wymaga przeglądu',released:'Fizycznie zwolniony',reserved:'Zarezerwowany',held:'Zajęty',active:'Aktywny',exercise:'Ćwiczenie',incident:'Incydent'}[s || ''] || s || 'Nie ustalono');
export const roleLabel = (s: string) => ({admin:'Administrator',administrator:'Administrator',coordinator:'Koordynator',operator:'Wykonawca',owner:'Właściciel usługi',observer:'Obserwator'}[s] || s);
