/** MOST's portable, versioned domain. Minutes are relative to referenceTime. */
export type Availability = 'available' | 'unavailable' | 'unknown';
export type VerificationStatus = 'confirmed' | 'unverified' | 'rejected' | 'conflicting';
export type Role = 'administrator' | 'coordinator' | 'owner' | 'operator' | 'observer';
export interface Provenance { source: string; checkedAt: string; synthetic?: boolean; evidenceIds?: string[] }
export interface Dependency { id: string; name: string; kind: 'leaf' | 'and' | 'or'; inputs: string[]; state?: Availability; confidence?: VerificationStatus; commonCauseId?: string; availableUntilMinute?: number; availableFromMinute?: number; provenance?: Provenance; version?: number }
export interface Service { id: string; name: string; outcome: string; unit: string; minimum: number; priority: number; weight: number; toleratedOutageMinutes: number; hardDeadlineMinute?: number; ownerId: string; deputyId?: string; location: string; version: number; provenance?: Provenance }
export interface Resource { id: string; name: string; type: 'person' | 'equipment' | 'consumable' | 'energy'; unit: string; quantity: number; state: Availability; confidence: VerificationStatus; location: string; skills: string[]; tags: string[]; capacity?: number; capacityUnit?: string; availableFromMinute?: number; availableUntilMinute?: number; occupied?: boolean; physicalReleaseConfirmed?: boolean; reconciliationRequired?: boolean; provenance: Provenance; dependencyId?: string }
export interface ResourceRequirement { id: string; type: Resource['type']; quantity: number; unit: string; resourceIds?: string[]; skills?: string[]; tags?: string[]; phase?: 'setup' | 'operation' | 'both'; consumptionPerMinute?: number; setupConsumption?: number; requiredCapacity?: number; capacityUnit?: string }
export interface OperatingMode { id: string; serviceId: string; name: string; level: number; dependencyId?: string; setupMinutes: number; autonomyMinutes?: number; requirements: ResourceRequirement[]; procedureId: string; procedureVersion: number; approved: boolean; verificationContractId: string; predecessors?: string[]; location?: string; provenance?: Provenance }
export interface Procedure { id: string; version: number; title: string; approved: boolean; approvedBy?: string; steps: string[]; prerequisites: string[]; safetyNote: string; provenance: Provenance }
export interface VerificationContract { id: string; version: number; modeId: string; title: string; expectedResult: string; metric: string; minimum: number; unit: string; validityMinutes: number; verifierRoles: Role[]; evidenceRequired: boolean; mandatory: boolean; simulated: boolean; provenance?: Provenance }
export interface Observation { id: string; original: string; subjectId: string; observedState?: Availability; authorId: string; source: string; observedAt: string; receivedAt: string; expiresAt?: string; verificationStatus: VerificationStatus; evidenceIds: string[]; kind?: 'observation' | 'instruction'; assessment?: string }
export interface Evidence { id: string; filename: string; mimeType: string; sha256: string; size: number; status: 'missing' | 'pending' | 'complete' | 'corrupt'; createdAt: string; simulated?: boolean }
export interface AssessmentImpact { computedAt: string; beforeModelRevision: number; modelRevision: number; subjectId: string; affectedServiceIds: string[]; affectedModeIds: string[]; affectedActionIds: string[]; dependencyChanges: { id: string; before: Availability; after: Availability }[]; missingChecks: { subjectId: string; state: Availability; question?: string; contact?: string; verificationMinutes?: number }[]; scope: 'dependency_and_resource_impact'; requiresReplanning: boolean }
export interface Assessment { id: string; subjectId: string; state: Availability; observationIds: string[]; contradictions: string[]; approvedBy: string; approvedAt: string; modelRevision: number; computedImpact?: AssessmentImpact }
export interface Reservation { id: string; resourceId: string; planId: string; actionId?: string; startMinute: number; endMinute: number; quantity: number; status: 'reserved' | 'in_use' | 'released' | 'consumed'; releaseConfirmedAt?: string; consumedQuantity?: number; unitIds?: string[] }
export interface AllocationScope { id: string; resourceIds: string[]; modeIds: string[]; authorizedUserId: string; validFrom: string; validUntil: string; modelRevision: number; allowLocalReplanning: boolean; conditions: string[] }
export interface Uncertainty { id: string; subjectId: string; question: string; verificationMinutes: number; contact: string; groupId?: string }
export interface TravelTime { from: string; to: string; minutes: number }
export interface DomainModel { schemaVersion: 1; id: string; organizationId: string; revision: number; name: string; synthetic: boolean; referenceTime: string; horizonMinutes: number; stepMinutes: number; services: Service[]; modes: OperatingMode[]; resources: Resource[]; dependencies: Dependency[]; procedures: Procedure[]; verificationContracts: VerificationContract[]; reservations: Reservation[]; uncertainties: Uncertainty[]; travelTimes: TravelTime[]; allocationScopes: AllocationScope[]; observations?: Observation[] }
export type Model = DomainModel;
export type SolverStatus = 'optimal' | 'feasible' | 'infeasible' | 'no_solution' | 'invalid_model' | 'cancelled';
/** Consumable segments describe uniform consumption across their interval; split segments when the rate changes. */
export interface Allocation { resourceId: string; requirementId: string; quantity: number; startMinute: number; endMinute: number; consumedQuantity?: number; unitIds?: string[] }
export interface PlanAction { id: string; serviceId: string; modeId: string; procedureId: string; procedureVersion: number; startMinute: number; readyMinute: number; endMinute: number; allocations: Allocation[]; predecessorIds: string[]; ownerId?: string; status: 'proposed' | 'approved' | 'accepted' | 'started' | 'completed' | 'blocked' | 'cancelled'; conditions: string[] }
export interface ServiceTimeline { serviceId: string; intervals: { startMinute: number; endMinute: number; modeId: string | null; level: number; meetsMinimum: boolean }[]; minimumMinutes: number; outageMinutes: number; firstMinimumMinute: number | null; maxOutageMinutes: number; toleranceExceeded: boolean }
export interface ValidationIssue { code: string; message: string; subjectId?: string; minute?: number }
export interface BlockedFragment { kind: 'dependency' | 'mode' | 'resource'; id: string; reasons: string[] }
export interface ValidationResult { valid: boolean; issues: ValidationIssue[]; warnings: ValidationIssue[]; blockedFragments?: BlockedFragment[] }
export interface PlanMetrics { minimumServiceMinutes: number; possibleServiceMinutes: number; outageServiceMinutes: number; simultaneousMinimumFromMinute: number | null; byPriority: Record<string, number>; normalizedShortfall: number; switches: number }
export interface SolverTimings { initializationMs: number; buildMs: number; solveMs: number; validationMs: number; totalMs: number; watchdogElapsedMs?: number }
export interface Plan { id: string; modelId: string; modelRevision: number; referenceTime: string; horizonMinutes: number; stepMinutes: number; createdAt: string; status: SolverStatus; approvalStatus: 'draft' | 'approved' | 'needs_review'; conditional: boolean; assumptions: { subjectId: string; state: Availability }[]; actions: PlanAction[]; timeline: ServiceTimeline[]; metrics: PlanMetrics; validation: ValidationResult; diagnostics: string[]; solver: { name: 'HiGHS'; stages: { name: string; status: string; objective?: number; elapsedMs: number }[]; budgetMs: number; timings: SolverTimings; completeHierarchy: boolean; interruption?: 'deadline' | 'cancelled' }; analysisScope: string[] }
export interface SolveOptions { budgetMs?: number; assumptions?: Record<string, Availability>; signal?: AbortSignal; wasmUrl?: string; now?: () => number; onSolverStart?: (noSolutionYet: Plan) => void; onProgress?: (validatedIncumbent: Plan) => void; onRankingProgress?: (partialRanking: RankingResult) => void }
export interface DependencyEvaluation { states: Record<string, Availability>; issues: ValidationIssue[]; reasons: Record<string, string[]> }
export interface CutSetResult { sets: string[][]; complete: boolean; explored: number; limit: number; issues: ValidationIssue[] }
export interface UncertaintyRanking { id: string; subjectIds: string[]; question: string; verificationMinutes: number; contact: string; availablePlan: Plan | null; unavailablePlan: Plan | null; improvementServiceMinutes: number; improvementByPriority: Record<string, number>; decisionChanges: boolean; approximate: boolean; analyzed: boolean; variants?: { assumptions: Record<string, Availability>; plan: Plan }[]; unexaminedCombinationCount?: string }
export interface RankingResult { items: UncertaintyRanking[]; complete: boolean; unexaminedIds: string[]; budgetMs: number; elapsedMs: number; scope: string[] }
export interface User { id: string; organizationId: string; username: string; displayName: string; role: Role; active: boolean }
export interface Device { id: string; organizationId: string; userId: string; name: string; authorized: boolean; lastSeenAt: string }
export interface Incident { id: string; name: string; kind: 'exercise' | 'incident'; status: 'open' | 'closed'; openedAt: string; closedAt?: string }
export interface VerificationResult { id: string; actionId: string; planId: string; planRevision: number; contractId: string; contractVersion: number; procedureVersion: number; outcome: 'passed' | 'failed' | 'unknown' | 'skipped'; measuredValue?: number; notes: string; evidenceIds: string[]; verifiedBy: string; observedAt: string; validUntil: string; simulated: boolean; invalidatedAt?: string; invalidationReason?: string }
export interface Command<T = Record<string, unknown>> { commandId: string; deviceId: string; organizationId: string; baseRevision: number; serverEpoch: string; dependsOn: string[]; type: string; schemaVersion: 1; payload: T; createdAt?: string }
export interface CommandResult { commandId: string; status: 'accepted' | 'duplicate' | 'conflict' | 'rejected' | 'waiting'; code?: string; message?: string; serverSeq?: number; revision?: number; data?: unknown }
export interface DomainEvent { id: string; commandId: string; organizationId: string; authorId: string; serverEpoch: string; serverSeq: number; type: string; entityId?: string; payload: Record<string, unknown>; createdAt: string }
export interface OfflineBundle { id: string; organizationId: string; userId: string; serverEpoch: string; serverSeq: number; modelRevision: number; createdAt: string; expiresAt: string; keyId: string; manifest: { path: string; sha256: string; size: number }[]; signature: string; scope: string[] }
export interface Snapshot { organizationId: string; serverEpoch: string; serverSeq: number; revision: number; model: DomainModel; incident: Incident; observations: Observation[]; evidence: Evidence[]; plans: Plan[]; verifications: VerificationResult[]; events: DomainEvent[]; users?: User[]; allocationScopes: AllocationScope[]; restored?: boolean }
export const SCHEMA_VERSION = 1 as const;
export const ROLE_LABELS: Record<Role, string> = { administrator: 'Administrator', coordinator: 'Koordynator', owner: 'Właściciel usługi', operator: 'Wykonawca', observer: 'Obserwator' };
export const AVAILABILITY_LABELS: Record<Availability, string> = { available: 'Dostępne', unavailable: 'Niedostępne', unknown: 'Nieznane' };
