import type { FastifyInstance } from 'fastify';
import { randomUUID } from 'node:crypto';
import { DomainError } from './domain.js';
import type { Store, User } from './store.js';

// Public access is an explicit, separate deployment mode. Never enable it over
// an existing organization, even when that organization happens to be synthetic.
export function assertPublicDemoStore(store: Store) {
  const count = (store.db.prepare('SELECT COUNT(*) AS count FROM organizations').get() as {count:number}).count;
  if (store.meta('publicDemo') !== '1' && count !== 0) throw new Error('Public demo requires a new, dedicated data directory.');
  store.setMeta('publicDemo', '1');
}

const html = `<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#172d32"><title>MOST | Uruchom demo</title><link rel="icon" href="/icon.svg"><link rel="stylesheet" href="/demo-style.css"></head><body><main><header><img src="/icon.svg" alt=""><strong>MOST</strong><span>CIĄGŁOŚĆ LOKALNYCH USŁUG</span></header><section class="intro"><div><p class="label">INTERAKTYWNE DEMO</p><h1>Cztery osoby.<br>Trzy usługi do utrzymania.</h1><p class="lead">Masz cztery osoby, jeden agregat i trzy usługi do utrzymania. Sprawdź, jak MOST przydziela zasoby i zmienia plan, gdy zabraknie jednej osoby.</p><button id="start" type="button">Uruchom demo <span aria-hidden="true">↗</span></button><p id="status" role="status" aria-live="polite">Własne ćwiczenie, bez konta. Dane syntetyczne.</p><a id="resume" href="/" hidden>Wróć do swojego ćwiczenia</a></div><aside><p class="label">TWOJA DECYZJA</p><h2>Pomoc. Łączność. Woda.</h2><p>Awaria routera odcina oba łącza. Rejestr lokalny i radio podtrzymują obsługę. Agregat zasila pompę.</p><div class="numbers"><strong>3<span>usługi</span></strong><strong>4<span>osoby</span></strong><strong>1<span>agregat</span></strong></div></aside></section><section class="steps" aria-label="Przebieg demonstracji"><article><span>01</span><h2>Zobacz wspólną przyczynę</h2><p>Otwórz Zależności. Światłowód i LTE zależą od tego samego routera.</p></article><article><span>02</span><h2>Ułóż wykonalny plan</h2><p>W Planach i przydziałach kliknij Oblicz nowy plan. Wyłącz dostępność Daniela i przelicz ponownie.</p></article><article><span>03</span><h2>Sprawdź, co zmienia wynik</h2><p>W Co sprawdzić porównaj odpowiedzi. Zatwierdź plan i przejdź do Moich zadań.</p></article></section><footer>DEFOZO SOFTWARE HOUSE · Michał Kiełtyka</footer></main><script src="/demo-start.js" defer></script></body></html>`;
const css = `*{box-sizing:border-box}body{margin:0;background:#f5f5ed;color:#172d32;font:16px/1.55 system-ui,-apple-system,Segoe UI,sans-serif}main{max-width:1220px;margin:auto;padding:32px 40px}header{display:flex;align-items:center;gap:14px}header img{width:42px}header strong{font-size:26px;letter-spacing:2px}header span{font-size:11px;font-weight:750;letter-spacing:1.8px;color:#53686b;margin-left:12px}.intro{display:grid;grid-template-columns:1.35fr 1fr;gap:74px;align-items:center;padding:68px 0}.label{font-size:11px;letter-spacing:2px;font-weight:800;color:#647640}h1{font-size:clamp(38px,4.8vw,62px);line-height:1.06;letter-spacing:-2.5px;margin:17px 0 26px}.lead{font-size:18px;color:#485f64;max-width:570px}button{margin-top:20px;border:0;border-radius:8px;background:#d4ed65;color:#172d32;font:750 17px system-ui;padding:17px 24px;cursor:pointer;min-width:235px;display:flex;justify-content:space-between;gap:35px;box-shadow:0 4px 0 #b6cc55}button:hover{background:#ddef98}button:disabled{cursor:wait}button:focus-visible,a:focus-visible{outline:3px solid #395991;outline-offset:5px}#status{font-size:13px;color:#53686b;margin-top:22px}#status.error{color:#a62c25}a{color:#172d32}aside{background:#172d32;border-radius:16px;color:#f8f9ef;padding:36px}aside .label{color:#d4ed65}aside h2{font-size:28px;line-height:1.2;letter-spacing:-.5px}aside p{color:#bbcacc}.numbers{display:flex;gap:42px;border-top:1px solid #486164;padding-top:20px;margin-top:28px}.numbers strong{font-size:43px;color:#d4ed65;line-height:1.1}.numbers span{display:block;font-size:13px;font-weight:450;color:#f8f9ef;margin-top:10px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:28px;padding:32px 0;border-top:1px solid #d5dcd2}.steps article>span{font-size:12px;font-weight:750;color:#66774a}.steps h2{font-size:19px;line-height:1.3}.steps p{font-size:14px;color:#53686b}footer{font-size:12px;color:#53686b;padding-top:25px;border-top:1px solid #d5dcd2}@media(max-width:760px){main{padding:23px}.intro{grid-template-columns:1fr;gap:32px;padding:34px 0}.steps{grid-template-columns:1fr;gap:8px}header span{display:none}h1{letter-spacing:-1.5px}aside{padding:27px}.numbers{justify-content:space-between;gap:20px}}`;
const script = `const button=document.getElementById('start');const status=document.getElementById('status');let csrf='';fetch('/api/session').then(r=>r.json()).then(s=>{csrf=s.csrfToken||'';if(s.user){document.getElementById('resume').hidden=false;button.firstChild.textContent='Nowe ćwiczenie ';}}).catch(()=>{});button.addEventListener('click',async()=>{button.disabled=true;status.classList.remove('error');status.textContent='Przygotowujemy Twoje ćwiczenie…';try{const r=await fetch('/api/auth/demo',{method:'POST',headers:{'Content-Type':'application/json',...(csrf?{'x-csrf-token':csrf}:{})},body:'{}'});const data=await r.json();if(!r.ok)throw new Error(data.message||'Nie udało się uruchomić ćwiczenia.');location.assign('/');}catch(e){status.textContent=e.message;status.classList.add('error');button.disabled=false;}});`;

export function registerPublicDemo(app: FastifyInstance, store: Store, session: (reply:any,user:User)=>unknown, seed: (store:Store,id:string,name:string)=>unknown) {
  app.get('/demo', (_request, reply) => reply.type('text/html; charset=utf-8').send(html));
  app.get('/demo-style.css', (_request, reply) => reply.type('text/css; charset=utf-8').send(css));
  app.get('/demo-start.js', (_request, reply) => reply.type('application/javascript; charset=utf-8').send(script));
  app.post('/api/auth/demo', {config:{rateLimit:{max:30,timeWindow:60_000,hook:'onRequest',keyGenerator:request=>`public-demo:${request.ip}`}}}, (request, reply) => {
    const user: User = {id:randomUUID(),organizationId:randomUUID(),username:`demo-${randomUUID()}`,displayName:'Koordynator ćwiczenia',role:'administrator',active:true};
    store.db.transaction(() => {
      const count = (store.db.prepare('SELECT COUNT(*) AS count FROM organizations').get() as {count:number}).count;
      if(count>=1000)throw new DomainError('demo_capacity','Wszystkie miejsca demonstracji są obecnie zajęte. Wróć do otwartego ćwiczenia.',429);
      seed(store,user.organizationId,'MOST · Twoje ćwiczenie');
      // Guest access is cookie-only. No shared account or guessable password.
      store.db.prepare('INSERT INTO users(id,organization_id,username,display_name,role,password_hash) VALUES (?,?,?,?,?,?)').run(user.id,user.organizationId,user.username,user.displayName,user.role,'!public-demo-cookie-only');
      store.event(store.read(user.organizationId),user.id,'demo.started',{synthetic:true});
    })();
    return session(reply,user);
  });
}
