/** Reopens already verified synthetic records to capture native Android frames.
 * No recalculation, model changes, account creation or server is involved.
 */
import {_android,expect as playwrightExpect,type Page} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFile,writeFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';

const sdkRoot=process.env.ANDROID_SDK_ROOT??(process.env.LOCALAPPDATA?join(process.env.LOCALAPPDATA,'Android','Sdk'):undefined);
const adb=process.env.ADB_PATH??(sdkRoot?join(sdkRoot,'platform-tools',process.platform==='win32'?'adb.exe':'adb'):'adb');
const serial=process.env.MOST_ANDROID_SERIAL??'emulator-5554';if(!serial.startsWith('emulator-'))throw new Error('Native evidence capture is restricted to the isolated emulator.');
const dir=resolve('artifacts/android'),report=JSON.parse(await readFile(join(dir,'verification.json'),'utf8'));
const failed=report.checks.filter((check:any)=>!check.passed),resumeExport=!report.passed&&failed.length===1&&String(failed[0].detail).includes('most-export-dialog.xml')&&report.checks.some((check:any)=>check.name==='Zachowano obydwa lokalne plany po restarcie'&&check.passed);
if(!report.passed&&!resumeExport)throw new Error('The full Android verification must pass, or have failed only in the known native export polling helper.');
const expect=playwrightExpect.configure({timeout:60000}),devices=await _android.devices({omitDriverInstall:true}),device=devices.find(d=>d.serial()===serial);for(const other of devices)if(other!==device)await other.close();if(!device)throw new Error('The test emulator is not attached.');device.setDefaultTimeout(120000);
const adbRun=(...args:string[])=>execFileSync(adb,['-s',serial,...args],{encoding:'utf8',windowsHide:true}).trim(),previousDebugApp=adbRun('shell','settings','get','global','debug_app');
let context:Awaited<ReturnType<typeof device.launchBrowser>>|undefined,page:Page;const frames:string[]=[];
const errors:string[]=[],recoveryChecks:{name:string;passed:boolean;detail?:unknown}[]=[];
async function navigate(label:string){await expect(page.locator('.app-shell')).toBeVisible();const menu=page.getByRole('button',{name:'Otwórz menu',exact:true});if(await menu.isVisible()){await menu.click();await expect(page.locator('.sidebar')).toHaveClass(/open/);}await page.getByRole('button',{name:label,exact:true}).click();}
async function frame(name:string,heading:string){const target=page.getByRole('heading',{name:heading,exact:true});await expect(target).toBeVisible();await target.evaluate(el=>el.scrollIntoView({block:'center'}));await device!.screenshot({path:join(dir,name)});frames.push(name);console.log(`Captured native frame ${name}`);}
async function finishExport(){
  const expectedIds=await page.evaluate(()=>new Promise<string[]>((ok,fail)=>{const open=indexedDB.open('most-device-v1');open.onerror=()=>fail(open.error);open.onsuccess=()=>{const db=open.result,read=db.transaction('proposals').objectStore('proposals').getAll();read.onsuccess=()=>{ok(read.result.filter(row=>row.type==='local.plan'&&[310,220].includes(row.payload.plan.metrics.minimumServiceMinutes)).map(row=>row.payload.plan.id));db.close();};read.onerror=()=>fail(read.error);};}));
  if(expectedIds.length<2)throw new Error('The previously verified plans are missing.');
  async function readMatchingDownload(){for(const name of adbRun('shell','ls','-1','/sdcard/Download').split(/\r?\n/).filter(name=>/^most-urzadzenie(?: \(\d+\))?\.json$/.test(name)).reverse())try{const text=adbRun('shell','cat',`"/sdcard/Download/${name}"`),value=JSON.parse(text);if(value.format==='most-device-export'&&expectedIds.every(id=>value.proposals.some((row:any)=>row.payload.plan?.id===id))&&value.outbox.some((row:any)=>row.command.type==='observation.create'&&row.status==='pending')){await writeFile(join(dir,'offline-device-export.json'),text);return {name,proposals:value.proposals.length,pending:value.outbox.filter((row:any)=>row.status==='pending').length};}}catch{}return null;}
  let saved=await readMatchingDownload();
  if(!saved){await page.getByRole('button',{name:'Eksport danych, plików i kolejki'}).click();await expect.poll(async()=>{saved=await readMatchingDownload();if(saved)return true;let xml='';try{adbRun('shell','uiautomator','dump','/sdcard/most-export-dialog.xml');xml=adbRun('shell','cat','/sdcard/most-export-dialog.xml');}catch{return false;}if(/download[^<]*again|pobrać[^<]*ponownie/i.test(xml)){const button=xml.match(/<node\b[^>]*\btext="(?:Download|Pobierz)"[^>]*\bbounds="\[(\d+),(\d+)\]\[(\d+),(\d+)\]"/);if(button)adbRun('shell','input','tap',String(Math.floor((Number(button[1])+Number(button[3]))/2)),String(Math.floor((Number(button[2])+Number(button[4]))/2)));}return false;},{timeout:90000,intervals:[1000,2000,4000]}).toBe(true);}
  recoveryChecks.push({name:'Eksport danych i kolejki odczytany z rzeczywistego pliku Android Download',passed:true,detail:saved});console.log('PASS native Android export contains the exact previously verified plan IDs and pending observation.');
}
try{
  adbRun('shell','am','set-debug-app','--persistent','com.android.chrome');context=await device.launchBrowser({offline:true,locale:'pl-PL',viewport:null});context.setDefaultTimeout(60000);page=await context.newPage();for(const older of context.pages())if(older!==page&&older.url().startsWith('http://localhost:8093/'))await older.close();page.on('pageerror',error=>errors.push(error.message));await page.goto('http://localhost:8093',{waitUntil:'domcontentloaded'});await expect(page.locator('.connection-status')).toContainText('Brak serwera');
  await navigate('To urządzenie');if(resumeExport)await finishExport();await frame('01-prepared.png','Pakiet lokalny przygotowany');
  await navigate('Plany i przydziały');await page.locator('.plan-tabs').getByRole('button').filter({hasText:'310 usługominut'}).first().click();await frame('02-four-person-plan.png','Wszystkie minima od 30. minuty');
  await page.locator('.plan-tabs').getByRole('button').filter({hasText:'220 usługominut'}).last().click();await frame('03-offline-three-person-plan.png','Nie utrzymamy jednocześnie wszystkich minimów');
  await navigate('Meldunki');const observation=page.getByText('Test Android offline: Daniel opuścił obsadę. Nowy plan potwierdza niedobór obsługi wody.',{exact:true});await expect(observation).toBeVisible();await observation.evaluate(el=>el.scrollIntoView({block:'center'}));await device.screenshot({path:join(dir,'04-offline-report-after-restart.png')});frames.push('04-offline-report-after-restart.png');
  expect(errors).toEqual([]);recoveryChecks.push({name:'Brak błędów JavaScript podczas wznowionego eksportu i odczytu',passed:true});
  const evidence={at:new Date().toISOString(),passed:true,originalAttempt:{path:'verification.json',passed:report.passed,failedChecks:failed},target:report.target,physicalPhone:false,releaseManifestHash:report.releaseManifestHash,nativeAndroidScreenshots:true,frames,resumedChecks:recoveryChecks,source:'Existing persisted plans and observation reopened offline after the application flow. No calculation or model mutation was performed. The original report is preserved unchanged; this evidence completes native export verification after its polling helper failed.'};await writeFile(join(dir,'verification-recovery.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence));
}finally{await context?.close().catch(()=>{});await device.close().catch(()=>{});if(previousDebugApp&&previousDebugApp!=='null')adbRun('shell','am','set-debug-app','--persistent',previousDebugApp);else adbRun('shell','am','clear-debug-app');}
